# 1. 데이터 불러오기



*   Api 를 이용한 데이터 불러오기
*   Csv 파일을 이용한 데이터 불러오기

1-1. 공공데이터 포탈 Open Api Xml 파일 불러오기

- 경찰청_범죄 발생 지역별 통계
- https://www.data.go.kr/tcs/dss/selectFileDataDetailView.do?publicDataPk=3074462

- 2015 년 Data

In [ ]:
# api를 불러오기 위한 코드

import requests

url = 'https://api.odcloud.kr/api/3074462/v1/uddi:7e73ac26-d0fa-4444-9c2e-81fdad4eff1b_201912061355?page=1&perPage=10&serviceKey=IxIRA9%2Fbxo%2FuirkWbTPaUQZ6EX%2BUvnfQNFMZjLDGTnECiZbmXvmgt2NaZjOYxBlBYLDxNAUYOM0pkV9aOgWqeQ%3D%3D'

response = requests.get(url)
print(response.text)
# 응답결과가 제대로 되었는 지 확인

{"currentCount":10,"data":[{"강원 강릉":1,"강원 동해":1,"강원 삼척":0,"강원 속초":0,"강원 원주":5,"강원 춘천":3,"강원 태백":0,"경기 고양":8,"경기 과천":2,"경기 광명":1,"경기 광주":4,"경기 구리":0,"경기 군포":1,"경기 김포":2,"경기 남양주":5,"경기 동두천":0,"경기 부천":7,"경기 성남":4,"경기 수원":6,"경기 시흥":9,"경기 안산":8,"경기 안성":0,"경기 안양":2,"경기 양주":1,"경기 여주":1,"경기 오산":2,"경기 용인":7,"경기 의왕":0,"경기 의정부":0,"경기 이천":3,"경기 파주":3,"경기 평택":1,"경기 포천":4,"경기 하남":1,"경기 화성":7,"경남 거제":2,"경남 김해":1,"경남 마산":0,"경남 밀양":1,"경남 사천":0,"경남 양산":2,"경남 진주":4,"경남 창원":7,"경남 통영":2,"경북 경산":1,"경북 경주":3,"경북 구미":3,"경북 김천":0,"경북 문경":1,"경북 상주":1,"경북 안동":2,"경북 영주":1,"경북 영천":0,"경북 포항":1,"광주":11,"기타도시":7,"대구":13,"대전":8,"도시이외":30,"범죄대분류":"강력범죄","범죄중분류":"살인기수","부산":20,"서울":67,"세종":2,"울산":12,"인천":17,"전남 광양":0,"전남 나주":0,"전남 목포":2,"전남 순천":1,"전남 여수":4,"전북 군산":0,"전북 김제":0,"전북 남원":0,"전북 익산":3,"전북 전주":4,"전북 정읍":0,"제주 서귀포":0,"제주 제주":11,"충남 계룡":0,"충남 공주":0,"충남 논산":3,"충남 당진":0,"충남 보령":3,"충남 서산":0,"충남 아산":5,"충남 천안":4,"충북 제천":2,"충북 청주":4,"충북 충주":1},{"강원 강릉":4,"강원 동해":1,"강원 삼척":0,"강원 속초":1,"강원 원주":5,"강원 춘천":3,"강원 태백":0,"경기 고양":9,"경기 과천":0,"경기 광명":1,"경기 광주":8,"경기 구리":3,"경기 군포":1,"경기 김포":3,"경기 남양주":6,"경기 동두천":3,"경기 부천":13,"경기 성남":6,"경기 수원":7,"경기 시흥":6,"경기 안산":12,"경기 안성":2,"경기 안양":6,"경기 양주":2,"경기 여주":3,"경기 오산":2,"경기 용인":5,"경기 의왕":0,"경기 의정부":7,"경기 이천":2,"경기 파주":4,"경기 평택":6,"경기 포천":3,"경기 하남":0,"경기 화성":8,"경남 거제":1,"경남 김해":7,"경남 마산":0,"경남 밀양":5,"경남 사천":5,"경남 양산":6,"경남 진주":0,"경남 창원":13,"경남 통영":2,"경북 경산":2,"경북 경주":4,"경북 구미":2,"경북 김천":1,"경북 문경":0,"경북 상주":0,"경북 안동":0,"경북 영주":0,"경북 영천":2,"경북 포항":7,"광주":7,"기타도시":4,"대구":23,"대전":16,"도시이외":44,"범죄대분류":"강력범죄","범죄중분류":"살인미수등","부산":41,"서울":96,"세종":1,"울산":11,"인천":34,"전남 광양":3,"전남 나주":1,"전남 목포":0,"전남 순천":1,"전남 여수":2,"전북 군산":6,"전북 김제":0,"전북 남원":0,"전북 익산":5,"전북 전주":7,"전북 정읍":1,"제주 서귀포":1,"제주 제주":16,"충남 계룡":0,"충남 공주":2,"충남 논산":3,"충남 당진":1,"충남 보령":5,"충남 서산":1,"충남 아산":4,"충남 천안":8,"충북 제천":5,"충북 청주":15,"충북 충주":1},{"강원 강릉":8,"강원 동해":0,"강원 삼척":0,"강원 속초":0,"강원 원주":9,"강원 춘천":9,"강원 태백":0,"경기 고양":14,"경기 과천":0,"경기 광명":4,"경기 광주":4,"경기 구리":6,"경기 군포":5,"경기 김포":7,"경기 남양주":12,"경기 동두천":0,"경기 부천":25,"경기 성남":30,"경기 수원":38,"경기 시흥":14,"경기 안산":42,"경기 안성":2,"경기 안양":7,"경기 양주":5,"경기 여주":5,"경기 오산":4,"경기 용인":11,"경기 의왕":1,"경기 의정부":15,"경기 이천":8,"경기 파주":5,"경기 평택":20,"경기 포천":3,"경기 하남":1,"경기 화성":12,"경남 거제":4,"경남 김해":17,"경남 마산":0,"경남 밀양":1,"경남 사천":4,"경남 양산":2,"경남 진주":13,"경남 창원":26,"경남 통영":3,"경북 경산":14,"경북 경주":9,"경북 구미":13,"경북 김천":3,"경북 문경":1,"경북 상주":1,"경북 안동":0,"경북 영주":9,"경북 영천":5,"경북 포항":10,"광주":44,"기타도시":4,"대구":60,"대전":64,"도시이외":65,"범죄대분류":"강력범죄","범죄중분류":"강도","부산":161,"서울":274,"세종":0,"울산":29,"인천":103,"전남 광양":1,"전남 나주":0,"전남 목포":9,"전남 순천":9,"전남 여수":6,"전북 군산":7,"전북 김제":1,"전북 남원":2,"전북 익산":14,"전북 전주":21,"전북 정읍":0,"제주 서귀포":4,"제주 제주":29,"충남 계룡":0,"충남 공주":0,"충남 논산":4,"충남 당진":3,"충남 보령":3,"충남 서산":6,"충남 아산":2,"충남 천안":22,"충북 제천":2,"충북 청주":30,"충북 충주":6},{"강원 강릉":28,"강원 동해":5,"강원 삼척":10,"강원 속초":6,"강원 원주":48,"강원 춘천":10,"강원 태백":1,"경기 고양":73,"경기 과천":0,"경기 광명":12,"경기 광주":25,"경기 구리":22,"경기 군포":26,"경기 김포":33,"경기 남양주":50,"경기 동두천":6,"경기 부천":105,"경기 성남":83,"경기 수원":157,"경기 시흥":36,"경기 안산":86,"경기 안성":23,"경기 안양":52,"경기 양주":19,"경기 여주":13,"경기 오산":23,"경기 용인":53,"경기 의왕":8,"경기 의정부":67,"경기 이천":23,"경기 파주":29,"경기 평택":50,"경기 포천":17,"경기 하남":11,"경기 화성":32,"경남 거제":23,"경남 김해":42,"경남 마산":0,"경남 밀양":10,"경남 사천":12,"경남 양산":35,"경남 진주":63,"경남 창원":85,"경남 통영":11,"경북 경산":23,"경북 경주":30,"경북 구미":50,"경북 김천":14,"경북 문경":5,"경북 상주":9,"경북 안동":25,"경북 영주":9,"경북 영천":9,"경북 포항":48,"광주":216,"기타도시":18,"대구":216,"대전":181,"도시이외":328,"범죄대분류":"강력범죄","범죄중분류":"강간","부산":383,"서울":969,"세종":3,"울산":132,"인천":304,"전남 광양":14,"전남 나주":4,"전남 목포":42,"전남 순천":34,"전남 여수":43,"전북 군산":21,"전북 김제":13,"전북 남원":11,"전북 익산":34,"전북 전주":68,"전북 정읍":16,"제주 서귀포":14,"제주 제주":64,"충남 계룡":1,"충남 공주":14,"충남 논산":13,"충남 당진":11,"충남 보령":10,"충남 서산":11,"충남 아산":27,"충남 천안":82,"충북 제천":15,"충북 청주":79,"충북 충주":15},{"강원 강릉":5,"강원 동해":1,"강원 삼척":0,"강원 속초":2,"강원 원주":2,"강원 춘천":9,"강원 태백":3,"경기 고양":9,"경기 과천":0,"경기 광명":0,"경기 광주":3,"경기 구리":1,"경기 군포":2,"경기 김포":5,"경기 남양주":2,"경기 동두천":0,"경기 부천":12,"경기 성남":12,"경기 수원":21,"경기 시흥":5,"경기 안산":2,"경기 안성":0,"경기 안양":4,"경기 양주":1,"경기 여주":0,"경기 오산":2,"경기 용인":9,"경기 의왕":0,"경기 의정부":10,"경기 이천":3,"경기 파주":3,"경기 평택":6,"경기 포천":1,"경기 하남":1,"경기 화성":4,"경남 거제":2,"경남 김해":1,"경남 마산":0,"경남 밀양":1,"경남 사천":1,"경남 양산":3,"경남 진주":1,"경남 창원":8,"경남 통영":1,"경북 경산":2,"경북 경주":2,"경북 구미":6,"경북 김천":1,"경북 문경":2,"경북 상주":1,"경북 안동":2,"경북 영주":1,"경북 영천":0,"경북 포항":4,"광주":17,"기타도시":0,"대구":21,"대전":14,"도시이외":33,"범죄대분류":"강력범죄","범죄중분류":"유사강간","부산":24,"서울":118,"세종":1,"울산":10,"인천":35,"전남 광양":1,"전남 나주":1,"전남 목포":1,"전남 순천":5,"전남 여수":2,"전북 군산":2,"전북 김제":0,"전북 남원":1,"전북 익산":3,"전북 전주":4,"전북 정읍":1,"제주 서귀포":1,"제주 제주":12,"충남 계룡":0,"충남 공주":1,"충남 논산":1,"충남 당진":0,"충남 보령":4,"충남 서산":7,"충남 아산":2,"충남 천안":6,"충북 제천":2,"충북 청주":4,"충북 충주":5},{"강원 강릉":56,"강원 동해":32,"강원 삼척":12,"강원 속초":20,"강원 원주":75,"강원 춘천":71,"강원 태백":8,"경기 고양":256,"경기 과천":20,"경기 광명":77,"경기 광주":49,"경기 구리":73,"경기 군포":67,"경기 김포":75,"경기 남양주":132,"경기 동두천":36,"경기 부천":291,"경기 성남":319,"경기 수원":425,"경기 시흥":171,"경기 안산":242,"경기 안성":42,"경기 안양":180,"경기 양주":44,"경기 여주":17,"경기 오산":81,"경기 용인":209,"경기 의왕":30,"경기 의정부":157,"경기 이천":59,"경기 파주":89,"경기 평택":161,"경기 포천":47,"경기 하남":25,"경기 화성":133,"경남 거제":62,"경남 김해":114,"경남 마산":1,"경남 밀양":20,"경남 사천":22,"경남 양산":59,"경남 진주":58,"경남 창원":172,"경남 통영":36,"경북 경산":54,"경북 경주":55,"경북 구미":81,"경북 김천":25,"경북 문경":12,"경북 상주":13,"경북 안동":36,"경북 영주":23,"경북 영천":14,"경북 포항":90,"광주":495,"기타도시":28,"대구":645,"대전":362,"도시이외":764,"범죄대분류":"강력범죄","범죄중분류":"강제추행","부산":991,"서울":4282,"세종":34,"울산":293,"인천":924,"전남 광양":19,"전남 나주":5,"전남 목포":81,"전남 순천":72,"전남 여수":51,"전북 군산":62,"전북 김제":17,"전북 남원":21,"전북 익산":59,"전북 전주":176,"전북 정읍":24,"제주 서귀포":32,"제주 제주":165,"충남 계룡":6,"충남 공주":27,"충남 논산":39,"충남 당진":32,"충남 보령":26,"충남 서산":48,"충남 아산":64,"충남 천안":177,"충북 제천":26,"충북 청주":229,"충북 충주":55},{"강원 강릉":1,"강원 동해":1,"강원 삼척":3,"강원 속초":2,"강원 원주":7,"강원 춘천":7,"강원 태백":2,"경기 고양":7,"경기 과천":0,"경기 광명":2,"경기 광주":2,"경기 구리":3,"경기 군포":0,"경기 김포":2,"경기 남양주":9,"경기 동두천":0,"경기 부천":7,"경기 성남":14,"경기 수원":23,"경기 시흥":6,"경기 안산":6,"경기 안성":3,"경기 안양":4,"경기 양주":3,"경기 여주":2,"경기 오산":2,"경기 용인":7,"경기 의왕":0,"경기 의정부":6,"경기 이천":4,"경기 파주":2,"경기 평택":4,"경기 포천":3,"경기 하남":0,"경기 화성":2,"경남 거제":1,"경남 김해":7,"경남 마산":0,"경남 밀양":1,"경남 사천":2,"경남 양산":1,"경남 진주":4,"경남 창원":13,"경남 통영":3,"경북 경산":1,"경북 경주":3,"경북 구미":4,"경북 김천":2,"경북 문경":1,"경북 상주":1,"경북 안동":4,"경북 영주":4,"경북 영천":0,"경북 포항":8,"광주":22,"기타도시":2,"대구":20,"대전":12,"도시이외":55,"범죄대분류":"강력범죄","범죄중분류":"기타강간강제추행등","부산":37,"서울":94,"세종":0,"울산":9,"인천":31,"전남 광양":2,"전남 나주":1,"전남 목포":3,"전남 순천":3,"전남 여수":1,"전북 군산":4,"전북 김제":3,"전북 남원":0,"전북 익산":2,"전북 전주":6,"전북 정읍":1,"제주 서귀포":1,"제주 제주":11,"충남 계룡":0,"충남 공주":1,"충남 논산":0,"충남 당진":1,"충남 보령":1,"충남 서산":2,"충남 아산":2,"충남 천안":10,"충북 제천":3,"충북 청주":12,"충북 충주":0},{"강원 강릉":5,"강원 동해":4,"강원 삼척":6,"강원 속초":3,"강원 원주":6,"강원 춘천":3,"강원 태백":0,"경기 고양":40,"경기 과천":1,"경기 광명":6,"경기 광주":6,"경기 구리":9,"경기 군포":7,"경기 김포":13,"경기 남양주":26,"경기 동두천":1,"경기 부천":38,"경기 성남":29,"경기 수원":40,"경기 시흥":25,"경기 안산":30,"경기 안성":4,"경기 안양":12,"경기 양주":8,"경기 여주":2,"경기 오산":4,"경기 용인":15,"경기 의왕":5,"경기 의정부":22,"경기 이천":10,"경기 파주":9,"경기 평택":19,"경기 포천":17,"경기 하남":4,"경기 화성":14,"경남 거제":12,"경남 김해":9,"경남 마산":0,"경남 밀양":2,"경남 사천":7,"경남 양산":9,"경남 진주":12,"경남 창원":33,"경남 통영":0,"경북 경산":5,"경북 경주":6,"경북 구미":10,"경북 김천":4,"경북 문경":2,"경북 상주":2,"경북 안동":8,"경북 영주":6,"경북 영천":3,"경북 포항":16,"광주":48,"기타도시":4,"대구":86,"대전":41,"도시이외":148,"범죄대분류":"강력범죄","범죄중분류":"방화","부산":117,"서울":315,"세종":5,"울산":36,"인천":94,"전남 광양":3,"전남 나주":0,"전남 목포":8,"전남 순천":7,"전남 여수":13,"전북 군산":9,"전북 김제":5,"전북 남원":3,"전북 익산":10,"전북 전주":11,"전북 정읍":6,"제주 서귀포":12,"제주 제주":23,"충남 계룡":0,"충남 공주":3,"충남 논산":8,"충남 당진":4,"충남 보령":4,"충남 서산":5,"충남 아산":4,"충남 천안":22,"충북 제천":3,"충북 청주":23,"충북 충주":4},{"강원 강릉":832,"강원 동해":288,"강원 삼척":188,"강원 속초":344,"강원 원주":1785,"강원 춘천":1132,"강원 태백":130,"경기 고양":3287,"경기 과천":170,"경기 광명":1234,"경기 광주":1072,"경기 구리":1042,"경기 군포":944,"경기 김포":1082,"경기 남양주":1888,"경기 동두천":410,"경기 부천":5048,"경기 성남":3941,"경기 수원":6487,"경기 시흥":1791,"경기 안산":4154,"경기 안성":844,"경기 안양":2142,"경기 양주":719,"경기 여주":417,"경기 오산":1164,"경기 용인":2791,"경기 의왕":307,"경기 의정부":2304,"경기 이천":655,"경기 파주":1136,"경기 평택":2160,"경기 포천":580,"경기 하남":575,"경기 화성":2178,"경남 거제":1395,"경남 김해":2739,"경남 마산":2,"경남 밀양":313,"경남 사천":358,"경남 양산":1205,"경남 진주":2032,"경남 창원":5860,"경남 통영":602,"경북 경산":1174,"경북 경주":1297,"경북 구미":2212,"경북 김천":506,"경북 문경":227,"경북 상주":322,"경북 안동":679,"경북 영주":245,"경북 영천":298,"경북 포항":2496,"광주":8438,"기타도시":643,"대구":12759,"대전":9495,"도시이외":11754,"범죄대분류":"절도범죄","범죄중분류":"절도","부산":20136,"서울":55280,"세종":638,"울산":5449,"인천":10679,"전남 광양":461,"전남 나주":46,"전남 목포":1520,"전남 순천":1188,"전남 여수":1049,"전북 군산":1470,"전북 김제":344,"전북 남원":276,"전북 익산":1391,"전북 전주":3402,"전북 정읍":565,"제주 서귀포":921,"제주 제주":3309,"충남 계룡":53,"충남 공주":423,"충남 논산":634,"충남 당진":1325,"충남 보령":681,"충남 서산":769,"충남 아산":1487,"충남 천안":3945,"충북 제천":524,"충북 청주":4691,"충북 충주":925},{"강원 강릉":352,"강원 동해":202,"강원 삼척":155,"강원 속초":174,"강원 원주":514,"강원 춘천":379,"강원 태백":82,"경기 고양":490,"경기 과천":22,"경기 광명":147,"경기 광주":237,"경기 구리":181,"경기 군포":142,"경기 김포":160,"경기 남양주":392,"경기 동두천":102,"경기 부천":524,"경기 성남":734,"경기 수원":938,"경기 시흥":295,"경기 안산":694,"경기 안성":141,"경기 안양":396,"경기 양주":157,"경기 여주":130,"경기 오산":149,"경기 용인":454,"경기 의왕":57,"경기 의정부":326,"경기 이천":161,"경기 파주":261,"경기 평택":460,"경기 포천":229,"경기 하남":104,"경기 화성":410,"경남 거제":490,"경남 김해":595,"경남 마산":1,"경남 밀양":134,"경남 사천":194,"경남 양산":307,"경남 진주":408,"경남 창원":1187,"경남 통영":321,"경북 경산":248,"경북 경주":347,"경북 구미":508,"경북 김천":200,"경북 문경":100,"경북 상주":127,"경북 안동":257,"경북 영주":134,"경북 영천":118,"경북 포항":616,"광주":1162,"기타도시":149,"대구":2736,"대전":1516,"도시이외":3941,"범죄대분류":"폭력범죄","범죄중분류":"상해","부산":4675,"서울":7174,"세종":117,"울산":1353,"인천":2179,"전남 광양":194,"전남 나주":5,"전남 목포":415,"전남 순천":354,"전남 여수":347,"전북 군산":283,"전북 김제":65,"전북 남원":101,"전북 익산":246,"전북 전주":496,"전북 정읍":108,"제주 서귀포":269,"제주 제주":532,"충남 계룡":24,"충남 공주":137,"충남 논산":155,"충남 당진":215,"충남 보령":137,"충남 서산":179,"충남 아산":341,"충남 천안":522,"충북 제천":172,"충북 청주":798,"충북 충주":265}],"matchCount":38,"page":1,"perPage":10,"totalCount":38}

In [ ]:
# json 파일 사용을 위한 패키지
import json
from pandas import json_normalize

In [ ]:
# 받아온 데이터를 json 파일 ( crime.json ) 로 저장
with open('crime.json', 'w', encoding = 'utf-8') as f:
    json.dump(response.text, f)

In [ ]:
# 저장된 데이터 불러오기

with open('crime.json', 'r') as f:
    # encoding='utf-8' 저장시에 이미 encoding을 해서 읽어올 때는 적지 않아도 될 것 같아요 !
    crime_json = json.load(f)

# print(type(crime_json))
# 파일 형식 확인 : <class 'str>

crime_json

'{"currentCount":10,"data":[{"강원 강릉":1,"강원 동해":1,"강원 삼척":0,"강원 속초":0,"강원 원주":5,"강원 춘천":3,"강원 태백":0,"경기 고양":8,"경기 과천":2,"경기 광명":1,"경기 광주":4,"경기 구리":0,"경기 군포":1,"경기 김포":2,"경기 남양주":5,"경기 동두천":0,"경기 부천":7,"경기 성남":4,"경기 수원":6,"경기 시흥":9,"경기 안산":8,"경기 안성":0,"경기 안양":2,"경기 양주":1,"경기 여주":1,"경기 오산":2,"경기 용인":7,"경기 의왕":0,"경기 의정부":0,"경기 이천":3,"경기 파주":3,"경기 평택":1,"경기 포천":4,"경기 하남":1,"경기 화성":7,"경남 거제":2,"경남 김해":1,"경남 마산":0,"경남 밀양":1,"경남 사천":0,"경남 양산":2,"경남 진주":4,"경남 창원":7,"경남 통영":2,"경북 경산":1,"경북 경주":3,"경북 구미":3,"경북 김천":0,"경북 문경":1,"경북 상주":1,"경북 안동":2,"경북 영주":1,"경북 영천":0,"경북 포항":1,"광주":11,"기타도시":7,"대구":13,"대전":8,"도시이외":30,"범죄대분류":"강력범죄","범죄중분류":"살인기수","부산":20,"서울":67,"세종":2,"울산":12,"인천":17,"전남 광양":0,"전남 나주":0,"전남 목포":2,"전남 순천":1,"전남 여수":4,"전북 군산":0,"전북 김제":0,"전북 남원":0,"전북 익산":3,"전북 전주":4,"전북 정읍":0,"제주 서귀포":0,"제주 제주":11,"충남 계룡":0,"충남 공주":0,"충남 논산":3,"충남 당진":0,"충남 보령":3,"충남 서산":0,"충남 아산":5,"충남 천안":4,"충북 제천":2,"충북 청주":4,"충북 충주":1},{"강원 강릉":4,"강원 동해":1,"강원 삼척":0,"강원 속초":1,"강원 원주":5,"강원 춘천":3,"강원 태백":0,"경기 고양":9,"경기 과천":0,"경기 광명":1,"경기 광주":8,"경기 구리":3,"경기 군포":1,"경기 김포":3,"경기 남양주":6,"경기 동두천":3,"경기 부천":13,"경기 성남":6,"경기 수원":7,"경기 시흥":6,"경기 안산":12,"경기 안성":2,"경기 안양":6,"경기 양주":2,"경기 여주":3,"경기 오산":2,"경기 용인":5,"경기 의왕":0,"경기 의정부":7,"경기 이천":2,"경기 파주":4,"경기 평택":6,"경기 포천":3,"경기 하남":0,"경기 화성":8,"경남 거제":1,"경남 김해":7,"경남 마산":0,"경남 밀양":5,"경남 사천":5,"경남 양산":6,"경남 진주":0,"경남 창원":13,"경남 통영":2,"경북 경산":2,"경북 경주":4,"경북 구미":2,"경북 김천":1,"경북 문경":0,"경북 상주":0,"경북 안동":0,"경북 영주":0,"경북 영천":2,"경북 포항":7,"광주":7,"기타도시":4,"대구":23,"대전":16,"도시이외":44,"범죄대분류":"강력범죄","범죄중분류":"살인미수등","부산":41,"서울":96,"세종":1,"울산":11,"인천":34,"전남 광양":3,"전남 나주":1,"전남 목포":0,"전남 순천":1,"전남 여수":2,"전북 군산":6,"전북 김제":0,"전북 남원":0,"전북 익산":5,"전북 전주":7,"전북 정읍":1,"제주 서귀포":1,"제주 제주":16,"충남 계룡":0,"충남 공주":2,"충남 논산":3,"충남 당진":1,"충남 보령":5,"충남 서산":1,"충남 아산":4,"충남 천안":8,"충북 제천":5,"충북 청주":15,"충북 충주":1},{"강원 강릉":8,"강원 동해":0,"강원 삼척":0,"강원 속초":0,"강원 원주":9,"강원 춘천":9,"강원 태백":0,"경기 고양":14,"경기 과천":0,"경기 광명":4,"경기 광주":4,"경기 구리":6,"경기 군포":5,"경기 김포":7,"경기 남양주":12,"경기 동두천":0,"경기 부천":25,"경기 성남":30,"경기 수원":38,"경기 시흥":14,"경기 안산":42,"경기 안성":2,"경기 안양":7,"경기 양주":5,"경기 여주":5,"경기 오산":4,"경기 용인":11,"경기 의왕":1,"경기 의정부":15,"경기 이천":8,"경기 파주":5,"경기 평택":20,"경기 포천":3,"경기 하남":1,"경기 화성":12,"경남 거제":4,"경남 김해":17,"경남 마산":0,"경남 밀양":1,"경남 사천":4,"경남 양산":2,"경남 진주":13,"경남 창원":26,"경남 통영":3,"경북 경산":14,"경북 경주":9,"경북 구미":13,"경북 김천":3,"경북 문경":1,"경북 상주":1,"경북 안동":0,"경북 영주":9,"경북 영천":5,"경북 포항":10,"광주":44,"기타도시":4,"대구":60,"대전":64,"도시이외":65,"범죄대분류":"강력범죄","범죄중분류":"강도","부산":161,"서울":274,"세종":0,"울산":29,"인천":103,"전남 광양":1,"전남 나주":0,"전남 목포":9,"전남 순천":9,"전남 여수":6,"전북 군산":7,"전북 김제":1,"전북 남원":2,"전북 익산":14,"전북 전주":21,"전북 정읍":0,"제주 서귀포":4,"제주 제주":29,"충남 계룡":0,"충남 공주":0,"충남 논산":4,"충남 당진":3,"충남 보령":3,"충남 서산":6,"충남 아산":2,"충남 천안":22,"충북 제천":2,"충북 청주":30,"충북 충주":6},{"강원 강릉":28,"강원 동해":5,"강원 삼척":10,"강원 속초":6,"강원 원주":48,"강원 춘천":10,"강원 태백":1,"경기 고양":73,"경기 과천":0,"경기 광명":12,"경기 광주":25,"경기 구리":22,"경기 군포":26,"경기 김포":33,"경기 남양주":50,"경기 동두천":6,"경기 부천":105,"경기 성남":83,"경기 수원":157,"경기 시흥":36,"경기 안산":86,"경기 안성":23,"경기 안양":52,"경기 양주":19,"경기 여주":13,"경기 오산":23,"경기 용인":53,"경기 의왕":8,"경기 의정부":67,"경기 이천":23,"경기 파주":29,"경기 평택":50,"경기 포천":17,"경기 하남":11,"경기 화성":32,"경남 거제":23,"경남 김해":42,"경남 마산":0,"경남 밀양":10,"경남 사천":12,"경남 양산":35,"경남 진주":63,"경남 창원":85,"경남 통영":11,"경북 경산":23,"경북 경주":30,"경북 구미":50,"경북 김천":14,"경북 문경":5,"경북 상주":9,"경북 안동":25,"경북 영주":9,"경북 영천":9,"경북 포항":48,"광주":216,"기타도시":18,"대구":216,"대전":181,"도시이외":328,"범죄대분류":"강력범죄","범죄중분류":"강간","부산":383,"서울":969,"세종":3,"울산":132,"인천":304,"전남 광양":14,"전남 나주":4,"전남 목포":42,"전남 순천":34,"전남 여수":43,"전북 군산":21,"전북 김제":13,"전북 남원":11,"전북 익산":34,"전북 전주":68,"전북 정읍":16,"제주 서귀포":14,"제주 제주":64,"충남 계룡":1,"충남 공주":14,"충남 논산":13,"충남 당진":11,"충남 보령":10,"충남 서산":11,"충남 아산":27,"충남 천안":82,"충북 제천":15,"충북 청주":79,"충북 충주":15},{"강원 강릉":5,"강원 동해":1,"강원 삼척":0,"강원 속초":2,"강원 원주":2,"강원 춘천":9,"강원 태백":3,"경기 고양":9,"경기 과천":0,"경기 광명":0,"경기 광주":3,"경기 구리":1,"경기 군포":2,"경기 김포":5,"경기 남양주":2,"경기 동두천":0,"경기 부천":12,"경기 성남":12,"경기 수원":21,"경기 시흥":5,"경기 안산":2,"경기 안성":0,"경기 안양":4,"경기 양주":1,"경기 여주":0,"경기 오산":2,"경기 용인":9,"경기 의왕":0,"경기 의정부":10,"경기 이천":3,"경기 파주":3,"경기 평택":6,"경기 포천":1,"경기 하남":1,"경기 화성":4,"경남 거제":2,"경남 김해":1,"경남 마산":0,"경남 밀양":1,"경남 사천":1,"경남 양산":3,"경남 진주":1,"경남 창원":8,"경남 통영":1,"경북 경산":2,"경북 경주":2,"경북 구미":6,"경북 김천":1,"경북 문경":2,"경북 상주":1,"경북 안동":2,"경북 영주":1,"경북 영천":0,"경북 포항":4,"광주":17,"기타도시":0,"대구":21,"대전":14,"도시이외":33,"범죄대분류":"강력범죄","범죄중분류":"유사강간","부산":24,"서울":118,"세종":1,"울산":10,"인천":35,"전남 광양":1,"전남 나주":1,"전남 목포":1,"전남 순천":5,"전남 여수":2,"전북 군산":2,"전북 김제":0,"전북 남원":1,"전북 익산":3,"전북 전주":4,"전북 정읍":1,"제주 서귀포":1,"제주 제주":12,"충남 계룡":0,"충남 공주":1,"충남 논산":1,"충남 당진":0,"충남 보령":4,"충남 서산":7,"충남 아산":2,"충남 천안":6,"충북 제천":2,"충북 청주":4,"충북 충주":5},{"강원 강릉":56,"강원 동해":32,"강원 삼척":12,"강원 속초":20,"강원 원주":75,"강원 춘천":71,"강원 태백":8,"경기 고양":256,"경기 과천":20,"경기 광명":77,"경기 광주":49,"경기 구리":73,"경기 군포":67,"경기 김포":75,"경기 남양주":132,"경기 동두천":36,"경기 부천":291,"경기 성남":319,"경기 수원":425,"경기 시흥":171,"경기 안산":242,"경기 안성":42,"경기 안양":180,"경기 양주":44,"경기 여주":17,"경기 오산":81,"경기 용인":209,"경기 의왕":30,"경기 의정부":157,"경기 이천":59,"경기 파주":89,"경기 평택":161,"경기 포천":47,"경기 하남":25,"경기 화성":133,"경남 거제":62,"경남 김해":114,"경남 마산":1,"경남 밀양":20,"경남 사천":22,"경남 양산":59,"경남 진주":58,"경남 창원":172,"경남 통영":36,"경북 경산":54,"경북 경주":55,"경북 구미":81,"경북 김천":25,"경북 문경":12,"경북 상주":13,"경북 안동":36,"경북 영주":23,"경북 영천":14,"경북 포항":90,"광주":495,"기타도시":28,"대구":645,"대전":362,"도시이외":764,"범죄대분류":"강력범죄","범죄중분류":"강제추행","부산":991,"서울":4282,"세종":34,"울산":293,"인천":924,"전남 광양":19,"전남 나주":5,"전남 목포":81,"전남 순천":72,"전남 여수":51,"전북 군산":62,"전북 김제":17,"전북 남원":21,"전북 익산":59,"전북 전주":176,"전북 정읍":24,"제주 서귀포":32,"제주 제주":165,"충남 계룡":6,"충남 공주":27,"충남 논산":39,"충남 당진":32,"충남 보령":26,"충남 서산":48,"충남 아산":64,"충남 천안":177,"충북 제천":26,"충북 청주":229,"충북 충주":55},{"강원 강릉":1,"강원 동해":1,"강원 삼척":3,"강원 속초":2,"강원 원주":7,"강원 춘천":7,"강원 태백":2,"경기 고양":7,"경기 과천":0,"경기 광명":2,"경기 광주":2,"경기 구리":3,"경기 군포":0,"경기 김포":2,"경기 남양주":9,"경기 동두천":0,"경기 부천":7,"경기 성남":14,"경기 수원":23,"경기 시흥":6,"경기 안산":6,"경기 안성":3,"경기 안양":4,"경기 양주":3,"경기 여주":2,"경기 오산":2,"경기 용인":7,"경기 의왕":0,"경기 의정부":6,"경기 이천":4,"경기 파주":2,"경기 평택":4,"경기 포천":3,"경기 하남":0,"경기 화성":2,"경남 거제":1,"경남 김해":7,"경남 마산":0,"경남 밀양":1,"경남 사천":2,"경남 양산":1,"경남 진주":4,"경남 창원":13,"경남 통영":3,"경북 경산":1,"경북 경주":3,"경북 구미":4,"경북 김천":2,"경북 문경":1,"경북 상주":1,"경북 안동":4,"경북 영주":4,"경북 영천":0,"경북 포항":8,"광주":22,"기타도시":2,"대구":20,"대전":12,"도시이외":55,"범죄대분류":"강력범죄","범죄중분류":"기타강간강제추행등","부산":37,"서울":94,"세종":0,"울산":9,"인천":31,"전남 광양":2,"전남 나주":1,"전남 목포":3,"전남 순천":3,"전남 여수":1,"전북 군산":4,"전북 김제":3,"전북 남원":0,"전북 익산":2,"전북 전주":6,"전북 정읍":1,"제주 서귀포":1,"제주 제주":11,"충남 계룡":0,"충남 공주":1,"충남 논산":0,"충남 당진":1,"충남 보령":1,"충남 서산":2,"충남 아산":2,"충남 천안":10,"충북 제천":3,"충북 청주":12,"충북 충주":0},{"강원 강릉":5,"강원 동해":4,"강원 삼척":6,"강원 속초":3,"강원 원주":6,"강원 춘천":3,"강원 태백":0,"경기 고양":40,"경기 과천":1,"경기 광명":6,"경기 광주":6,"경기 구리":9,"경기 군포":7,"경기 김포":13,"경기 남양주":26,"경기 동두천":1,"경기 부천":38,"경기 성남":29,"경기 수원":40,"경기 시흥":25,"경기 안산":30,"경기 안성":4,"경기 안양":12,"경기 양주":8,"경기 여주":2,"경기 오산":4,"경기 용인":15,"경기 의왕":5,"경기 의정부":22,"경기 이천":10,"경기 파주":9,"경기 평택":19,"경기 포천":17,"경기 하남":4,"경기 화성":14,"경남 거제":12,"경남 김해":9,"경남 마산":0,"경남 밀양":2,"경남 사천":7,"경남 양산":9,"경남 진주":12,"경남 창원":33,"경남 통영":0,"경북 경산":5,"경북 경주":6,"경북 구미":10,"경북 김천":4,"경북 문경":2,"경북 상주":2,"경북 안동":8,"경북 영주":6,"경북 영천":3,"경북 포항":16,"광주":48,"기타도시":4,"대구":86,"대전":41,"도시이외":148,"범죄대분류":"강력범죄","범죄중분류":"방화","부산":117,"서울":315,"세종":5,"울산":36,"인천":94,"전남 광양":3,"전남 나주":0,"전남 목포":8,"전남 순천":7,"전남 여수":13,"전북 군산":9,"전북 김제":5,"전북 남원":3,"전북 익산":10,"전북 전주":11,"전북 정읍":6,"제주 서귀포":12,"제주 제주":23,"충남 계룡":0,"충남 공주":3,"충남 논산":8,"충남 당진":4,"충남 보령":4,"충남 서산":5,"충남 아산":4,"충남 천안":22,"충북 제천":3,"충북 청주":23,"충북 충주":4},{"강원 강릉":832,"강원 동해":288,"강원 삼척":188,"강원 속초":344,"강원 원주":1785,"강원 춘천":1132,"강원 태백":130,"경기 고양":3287,"경기 과천":170,"경기 광명":1234,"경기 광주":1072,"경기 구리":1042,"경기 군포":944,"경기 김포":1082,"경기 남양주":1888,"경기 동두천":410,"경기 부천":5048,"경기 성남":3941,"경기 수원":6487,"경기 시흥":1791,"경기 안산":4154,"경기 안성":844,"경기 안양":2142,"경기 양주":719,"경기 여주":417,"경기 오산":1164,"경기 용인":2791,"경기 의왕":307,"경기 의정부":2304,"경기 이천":655,"경기 파주":1136,"경기 평택":2160,"경기 포천":580,"경기 하남":575,"경기 화성":2178,"경남 거제":1395,"경남 김해":2739,"경남 마산":2,"경남 밀양":313,"경남 사천":358,"경남 양산":1205,"경남 진주":2032,"경남 창원":5860,"경남 통영":602,"경북 경산":1174,"경북 경주":1297,"경북 구미":2212,"경북 김천":506,"경북 문경":227,"경북 상주":322,"경북 안동":679,"경북 영주":245,"경북 영천":298,"경북 포항":2496,"광주":8438,"기타도시":643,"대구":12759,"대전":9495,"도시이외":11754,"범죄대분류":"절도범죄","범죄중분류":"절도","부산":20136,"서울":55280,"세종":638,"울산":5449,"인천":10679,"전남 광양":461,"전남 나주":46,"전남 목포":1520,"전남 순천":1188,"전남 여수":1049,"전북 군산":1470,"전북 김제":344,"전북 남원":276,"전북 익산":1391,"전북 전주":3402,"전북 정읍":565,"제주 서귀포":921,"제주 제주":3309,"충남 계룡":53,"충남 공주":423,"충남 논산":634,"충남 당진":1325,"충남 보령":681,"충남 서산":769,"충남 아산":1487,"충남 천안":3945,"충북 제천":524,"충북 청주":4691,"충북 충주":925},{"강원 강릉":352,"강원 동해":202,"강원 삼척":155,"강원 속초":174,"강원 원주":514,"강원 춘천":379,"강원 태백":82,"경기 고양":490,"경기 과천":22,"경기 광명":147,"경기 광주":237,"경기 구리":181,"경기 군포":142,"경기 김포":160,"경기 남양주":392,"경기 동두천":102,"경기 부천":524,"경기 성남":734,"경기 수원":938,"경기 시흥":295,"경기 안산":694,"경기 안성":141,"경기 안양":396,"경기 양주":157,"경기 여주":130,"경기 오산":149,"경기 용인":454,"경기 의왕":57,"경기 의정부":326,"경기 이천":161,"경기 파주":261,"경기 평택":460,"경기 포천":229,"경기 하남":104,"경기 화성":410,"경남 거제":490,"경남 김해":595,"경남 마산":1,"경남 밀양":134,"경남 사천":194,"경남 양산":307,"경남 진주":408,"경남 창원":1187,"경남 통영":321,"경북 경산":248,"경북 경주":347,"경북 구미":508,"경북 김천":200,"경북 문경":100,"경북 상주":127,"경북 안동":257,"경북 영주":134,"경북 영천":118,"경북 포항":616,"광주":1162,"기타도시":149,"대구":2736,"대전":1516,"도시이외":3941,"범죄대분류":"폭력범죄","범죄중분류":"상해","부산":4675,"서울":7174,"세종":117,"울산":1353,"인천":2179,"전남 광양":194,"전남 나주":5,"전남 목포":415,"전남 순천":354,"전남 여수":347,"전북 군산":283,"전북 김제":65,"전북 남원":101,"전북 익산":246,"전북 전주":496,"전북 정읍":108,"제주 서귀포":269,"제주 제주":532,"충남 계룡":24,"충남 공주":137,"충남 논산":155,"충남 당진":215,"충남 보령":137,"충남 서산":179,"충남 아산":341,"충남 천안":522,"충북 제천":172,"충북 청주":798,"충북 충주":265}],"matchCount":38,"page":1,"perPage":10,"totalCount":38}\n'

In [ ]:
result = json.loads(crime_json)
# result
# json 파일을 dict로 result 변수에 저장

In [ ]:
result.keys()
# 필요한 데이터를 찾기 위해 파고 들어가는 과정

dict_keys(['currentCount', 'data', 'matchCount', 'page', 'perPage', 'totalCount'])

In [ ]:
result['data']
# 가지고 있는 데이터 내용 : 범죄대분류, 범죄중분류, 지역, 수

## data를 확인해보면, 일반데이터와 범죄의 분류가 같은 차원 ..

[{'강원 강릉': 1,
  '강원 동해': 1,
  '강원 삼척': 0,
  '강원 속초': 0,
  '강원 원주': 5,
  '강원 춘천': 3,
  '강원 태백': 0,
  '경기 고양': 8,
  '경기 과천': 2,
  '경기 광명': 1,
  '경기 광주': 4,
  '경기 구리': 0,
  '경기 군포': 1,
  '경기 김포': 2,
  '경기 남양주': 5,
  '경기 동두천': 0,
  '경기 부천': 7,
  '경기 성남': 4,
  '경기 수원': 6,
  '경기 시흥': 9,
  '경기 안산': 8,
  '경기 안성': 0,
  '경기 안양': 2,
  '경기 양주': 1,
  '경기 여주': 1,
  '경기 오산': 2,
  '경기 용인': 7,
  '경기 의왕': 0,
  '경기 의정부': 0,
  '경기 이천': 3,
  '경기 파주': 3,
  '경기 평택': 1,
  '경기 포천': 4,
  '경기 하남': 1,
  '경기 화성': 7,
  '경남 거제': 2,
  '경남 김해': 1,
  '경남 마산': 0,
  '경남 밀양': 1,
  '경남 사천': 0,
  '경남 양산': 2,
  '경남 진주': 4,
  '경남 창원': 7,
  '경남 통영': 2,
  '경북 경산': 1,
  '경북 경주': 3,
  '경북 구미': 3,
  '경북 김천': 0,
  '경북 문경': 1,
  '경북 상주': 1,
  '경북 안동': 2,
  '경북 영주': 1,
  '경북 영천': 0,
  '경북 포항': 1,
  '광주': 11,
  '기타도시': 7,
  '대구': 13,
  '대전': 8,
  '도시이외': 30,
  '범죄대분류': '강력범죄',
  '범죄중분류': '살인기수',
  '부산': 20,
  '서울': 67,
  '세종': 2,
  '울산': 12,
  '인천': 17,
  '전남 광양': 0,
  '전남 나주': 0,
  '전남 목포': 2,
  '전남 순천': 1,
  '전남 여수': 4,
  '전북 군산': 0,
  '전북 김제': 0,
  '전북 남원': 0,
  '전북 익산': 3,
  '전북 전주': 4,
  '전북 정읍': 0,
  '제주 서귀포': 0,
  '제주 제주': 11,
  '충남 계룡': 0,
  '충남 공주': 0,
  '충남 논산': 3,
  '충남 당진': 0,
  '충남 보령': 3,
  '충남 서산': 0,
  '충남 아산': 5,
  '충남 천안': 4,
  '충북 제천': 2,
  '충북 청주': 4,
  '충북 충주': 1},
 {'강원 강릉': 4,
  '강원 동해': 1,
  '강원 삼척': 0,
  '강원 속초': 1,
  '강원 원주': 5,
  '강원 춘천': 3,
  '강원 태백': 0,
  '경기 고양': 9,
  '경기 과천': 0,
  '경기 광명': 1,
  '경기 광주': 8,
  '경기 구리': 3,
  '경기 군포': 1,
  '경기 김포': 3,
  '경기 남양주': 6,
  '경기 동두천': 3,
  '경기 부천': 13,
  '경기 성남': 6,
  '경기 수원': 7,
  '경기 시흥': 6,
  '경기 안산': 12,
  '경기 안성': 2,
  '경기 안양': 6,
  '경기 양주': 2,
  '경기 여주': 3,
  '경기 오산': 2,
  '경기 용인': 5,
  '경기 의왕': 0,
  '경기 의정부': 7,
  '경기 이천': 2,
  '경기 파주': 4,
  '경기 평택': 6,
  '경기 포천': 3,
  '경기 하남': 0,
  '경기 화성': 8,
  '경남 거제': 1,
  '경남 김해': 7,
  '경남 마산': 0,
  '경남 밀양': 5,
  '경남 사천': 5,
  '경남 양산': 6,
  '경남 진주': 0,
  '경남 창원': 13,
  '경남 통영': 2,
  '경북 경산': 2,
  '경북 경주': 4,
  '경북 구미': 2,
  '경북 김천': 1,
  '경북 문경': 0,
  '경북 상주': 0,
  '경북 안동': 0,
  '경북 영주': 0,
  '경북 영천': 2,
  '경북 포항': 7,
  '광주': 7,
  '기타도시': 4,
  '대구': 23,
  '대전': 16,
  '도시이외': 44,
  '범죄대분류': '강력범죄',
  '범죄중분류': '살인미수등',
  '부산': 41,
  '서울': 96,
  '세종': 1,
  '울산': 11,
  '인천': 34,
  '전남 광양': 3,
  '전남 나주': 1,
  '전남 목포': 0,
  '전남 순천': 1,
  '전남 여수': 2,
  '전북 군산': 6,
  '전북 김제': 0,
  '전북 남원': 0,
  '전북 익산': 5,
  '전북 전주': 7,
  '전북 정읍': 1,
  '제주 서귀포': 1,
  '제주 제주': 16,
  '충남 계룡': 0,
  '충남 공주': 2,
  '충남 논산': 3,
  '충남 당진': 1,
  '충남 보령': 5,
  '충남 서산': 1,
  '충남 아산': 4,
  '충남 천안': 8,
  '충북 제천': 5,
  '충북 청주': 15,
  '충북 충주': 1},
 {'강원 강릉': 8,
  '강원 동해': 0,
  '강원 삼척': 0,
  '강원 속초': 0,
  '강원 원주': 9,
  '강원 춘천': 9,
  '강원 태백': 0,
  '경기 고양': 14,
  '경기 과천': 0,
  '경기 광명': 4,
  '경기 광주': 4,
  '경기 구리': 6,
  '경기 군포': 5,
  '경기 김포': 7,
  '경기 남양주': 12,
  '경기 동두천': 0,
  '경기 부천': 25,
  '경기 성남': 30,
  '경기 수원': 38,
  '경기 시흥': 14,
  '경기 안산': 42,
  '경기 안성': 2,
  '경기 안양': 7,
  '경기 양주': 5,
  '경기 여주': 5,
  '경기 오산': 4,
  '경기 용인': 11,
  '경기 의왕': 1,
  '경기 의정부': 15,
  '경기 이천': 8,
  '경기 파주': 5,
  '경기 평택': 20,
  '경기 포천': 3,
  '경기 하남': 1,
  '경기 화성': 12,
  '경남 거제': 4,
  '경남 김해': 17,
  '경남 마산': 0,
  '경남 밀양': 1,
  '경남 사천': 4,
  '경남 양산': 2,
  '경남 진주': 13,
  '경남 창원': 26,
  '경남 통영': 3,
  '경북 경산': 14,
  '경북 경주': 9,
  '경북 구미': 13,
  '경북 김천': 3,
  '경북 문경': 1,
  '경북 상주': 1,
  '경북 안동': 0,
  '경북 영주': 9,
  '경북 영천': 5,
  '경북 포항': 10,
  '광주': 44,
  '기타도시': 4,
  '대구': 60,
  '대전': 64,
  '도시이외': 65,
  '범죄대분류': '강력범죄',
  '범죄중분류': '강도',
  '부산': 161,
  '서울': 274,
  '세종': 0,
  '울산': 29,
  '인천': 103,
  '전남 광양': 1,
  '전남 나주': 0,
  '전남 목포': 9,
  '전남 순천': 9,
  '전남 여수': 6,
  '전북 군산': 7,
  '전북 김제': 1,
  '전북 남원': 2,
  '전북 익산': 14,
  '전북 전주': 21,
  '전북 정읍': 0,
  '제주 서귀포': 4,
  '제주 제주': 29,
  '충남 계룡': 0,
  '충남 공주': 0,
  '충남 논산': 4,
  '충남 당진': 3,
  '충남 보령': 3,
  '충남 서산': 6,
  '충남 아산': 2,
  '충남 천안': 22,
  '충북 제천': 2,
  '충북 청주': 30,
  '충북 충주': 6},
 {'강원 강릉': 28,
  '강원 동해': 5,
  '강원 삼척': 10,
  '강원 속초': 6,
  '강원 원주': 48,
  '강원 춘천': 10,
  '강원 태백': 1,
  '경기 고양': 73,
  '경기 과천': 0,
  '경기 광명': 12,
  '경기 광주': 25,
  '경기 구리': 22,
  '경기 군포': 26,
  '경기 김포': 33,
  '경기 남양주': 50,
  '경기 동두천': 6,
  '경기 부천': 105,
  '경기 성남': 83,
  '경기 수원': 157,
  '경기 시흥': 36,
  '경기 안산': 86,
  '경기 안성': 23,
  '경기 안양': 52,
  '경기 양주': 19,
  '경기 여주': 13,
  '경기 오산': 23,
  '경기 용인': 53,
  '경기 의왕': 8,
  '경기 의정부': 67,
  '경기 이천': 23,
  '경기 파주': 29,
  '경기 평택': 50,
  '경기 포천': 17,
  '경기 하남': 11,
  '경기 화성': 32,
  '경남 거제': 23,
  '경남 김해': 42,
  '경남 마산': 0,
  '경남 밀양': 10,
  '경남 사천': 12,
  '경남 양산': 35,
  '경남 진주': 63,
  '경남 창원': 85,
  '경남 통영': 11,
  '경북 경산': 23,
  '경북 경주': 30,
  '경북 구미': 50,
  '경북 김천': 14,
  '경북 문경': 5,
  '경북 상주': 9,
  '경북 안동': 25,
  '경북 영주': 9,
  '경북 영천': 9,
  '경북 포항': 48,
  '광주': 216,
  '기타도시': 18,
  '대구': 216,
  '대전': 181,
  '도시이외': 328,
  '범죄대분류': '강력범죄',
  '범죄중분류': '강간',
  '부산': 383,
  '서울': 969,
  '세종': 3,
  '울산': 132,
  '인천': 304,
  '전남 광양': 14,
  '전남 나주': 4,
  '전남 목포': 42,
  '전남 순천': 34,
  '전남 여수': 43,
  '전북 군산': 21,
  '전북 김제': 13,
  '전북 남원': 11,
  '전북 익산': 34,
  '전북 전주': 68,
  '전북 정읍': 16,
  '제주 서귀포': 14,
  '제주 제주': 64,
  '충남 계룡': 1,
  '충남 공주': 14,
  '충남 논산': 13,
  '충남 당진': 11,
  '충남 보령': 10,
  '충남 서산': 11,
  '충남 아산': 27,
  '충남 천안': 82,
  '충북 제천': 15,
  '충북 청주': 79,
  '충북 충주': 15},
 {'강원 강릉': 5,
  '강원 동해': 1,
  '강원 삼척': 0,
  '강원 속초': 2,
  '강원 원주': 2,
  '강원 춘천': 9,
  '강원 태백': 3,
  '경기 고양': 9,
  '경기 과천': 0,
  '경기 광명': 0,
  '경기 광주': 3,
  '경기 구리': 1,
  '경기 군포': 2,
  '경기 김포': 5,
  '경기 남양주': 2,
  '경기 동두천': 0,
  '경기 부천': 12,
  '경기 성남': 12,
  '경기 수원': 21,
  '경기 시흥': 5,
  '경기 안산': 2,
  '경기 안성': 0,
  '경기 안양': 4,
  '경기 양주': 1,
  '경기 여주': 0,
  '경기 오산': 2,
  '경기 용인': 9,
  '경기 의왕': 0,
  '경기 의정부': 10,
  '경기 이천': 3,
  '경기 파주': 3,
  '경기 평택': 6,
  '경기 포천': 1,
  '경기 하남': 1,
  '경기 화성': 4,
  '경남 거제': 2,
  '경남 김해': 1,
  '경남 마산': 0,
  '경남 밀양': 1,
  '경남 사천': 1,
  '경남 양산': 3,
  '경남 진주': 1,
  '경남 창원': 8,
  '경남 통영': 1,
  '경북 경산': 2,
  '경북 경주': 2,
  '경북 구미': 6,
  '경북 김천': 1,
  '경북 문경': 2,
  '경북 상주': 1,
  '경북 안동': 2,
  '경북 영주': 1,
  '경북 영천': 0,
  '경북 포항': 4,
  '광주': 17,
  '기타도시': 0,
  '대구': 21,
  '대전': 14,
  '도시이외': 33,
  '범죄대분류': '강력범죄',
  '범죄중분류': '유사강간',
  '부산': 24,
  '서울': 118,
  '세종': 1,
  '울산': 10,
  '인천': 35,
  '전남 광양': 1,
  '전남 나주': 1,
  '전남 목포': 1,
  '전남 순천': 5,
  '전남 여수': 2,
  '전북 군산': 2,
  '전북 김제': 0,
  '전북 남원': 1,
  '전북 익산': 3,
  '전북 전주': 4,
  '전북 정읍': 1,
  '제주 서귀포': 1,
  '제주 제주': 12,
  '충남 계룡': 0,
  '충남 공주': 1,
  '충남 논산': 1,
  '충남 당진': 0,
  '충남 보령': 4,
  '충남 서산': 7,
  '충남 아산': 2,
  '충남 천안': 6,
  '충북 제천': 2,
  '충북 청주': 4,
  '충북 충주': 5},
 {'강원 강릉': 56,
  '강원 동해': 32,
  '강원 삼척': 12,
  '강원 속초': 20,
  '강원 원주': 75,
  '강원 춘천': 71,
  '강원 태백': 8,
  '경기 고양': 256,
  '경기 과천': 20,
  '경기 광명': 77,
  '경기 광주': 49,
  '경기 구리': 73,
  '경기 군포': 67,
  '경기 김포': 75,
  '경기 남양주': 132,
  '경기 동두천': 36,
  '경기 부천': 291,
  '경기 성남': 319,
  '경기 수원': 425,
  '경기 시흥': 171,
  '경기 안산': 242,
  '경기 안성': 42,
  '경기 안양': 180,
  '경기 양주': 44,
  '경기 여주': 17,
  '경기 오산': 81,
  '경기 용인': 209,
  '경기 의왕': 30,
  '경기 의정부': 157,
  '경기 이천': 59,
  '경기 파주': 89,
  '경기 평택': 161,
  '경기 포천': 47,
  '경기 하남': 25,
  '경기 화성': 133,
  '경남 거제': 62,
  '경남 김해': 114,
  '경남 마산': 1,
  '경남 밀양': 20,
  '경남 사천': 22,
  '경남 양산': 59,
  '경남 진주': 58,
  '경남 창원': 172,
  '경남 통영': 36,
  '경북 경산': 54,
  '경북 경주': 55,
  '경북 구미': 81,
  '경북 김천': 25,
  '경북 문경': 12,
  '경북 상주': 13,
  '경북 안동': 36,
  '경북 영주': 23,
  '경북 영천': 14,
  '경북 포항': 90,
  '광주': 495,
  '기타도시': 28,
  '대구': 645,
  '대전': 362,
  '도시이외': 764,
  '범죄대분류': '강력범죄',
  '범죄중분류': '강제추행',
  '부산': 991,
  '서울': 4282,
  '세종': 34,
  '울산': 293,
  '인천': 924,
  '전남 광양': 19,
  '전남 나주': 5,
  '전남 목포': 81,
  '전남 순천': 72,
  '전남 여수': 51,
  '전북 군산': 62,
  '전북 김제': 17,
  '전북 남원': 21,
  '전북 익산': 59,
  '전북 전주': 176,
  '전북 정읍': 24,
  '제주 서귀포': 32,
  '제주 제주': 165,
  '충남 계룡': 6,
  '충남 공주': 27,
  '충남 논산': 39,
  '충남 당진': 32,
  '충남 보령': 26,
  '충남 서산': 48,
  '충남 아산': 64,
  '충남 천안': 177,
  '충북 제천': 26,
  '충북 청주': 229,
  '충북 충주': 55},
 {'강원 강릉': 1,
  '강원 동해': 1,
  '강원 삼척': 3,
  '강원 속초': 2,
  '강원 원주': 7,
  '강원 춘천': 7,
  '강원 태백': 2,
  '경기 고양': 7,
  '경기 과천': 0,
  '경기 광명': 2,
  '경기 광주': 2,
  '경기 구리': 3,
  '경기 군포': 0,
  '경기 김포': 2,
  '경기 남양주': 9,
  '경기 동두천': 0,
  '경기 부천': 7,
  '경기 성남': 14,
  '경기 수원': 23,
  '경기 시흥': 6,
  '경기 안산': 6,
  '경기 안성': 3,
  '경기 안양': 4,
  '경기 양주': 3,
  '경기 여주': 2,
  '경기 오산': 2,
  '경기 용인': 7,
  '경기 의왕': 0,
  '경기 의정부': 6,
  '경기 이천': 4,
  '경기 파주': 2,
  '경기 평택': 4,
  '경기 포천': 3,
  '경기 하남': 0,
  '경기 화성': 2,
  '경남 거제': 1,
  '경남 김해': 7,
  '경남 마산': 0,
  '경남 밀양': 1,
  '경남 사천': 2,
  '경남 양산': 1,
  '경남 진주': 4,
  '경남 창원': 13,
  '경남 통영': 3,
  '경북 경산': 1,
  '경북 경주': 3,
  '경북 구미': 4,
  '경북 김천': 2,
  '경북 문경': 1,
  '경북 상주': 1,
  '경북 안동': 4,
  '경북 영주': 4,
  '경북 영천': 0,
  '경북 포항': 8,
  '광주': 22,
  '기타도시': 2,
  '대구': 20,
  '대전': 12,
  '도시이외': 55,
  '범죄대분류': '강력범죄',
  '범죄중분류': '기타강간강제추행등',
  '부산': 37,
  '서울': 94,
  '세종': 0,
  '울산': 9,
  '인천': 31,
  '전남 광양': 2,
  '전남 나주': 1,
  '전남 목포': 3,
  '전남 순천': 3,
  '전남 여수': 1,
  '전북 군산': 4,
  '전북 김제': 3,
  '전북 남원': 0,
  '전북 익산': 2,
  '전북 전주': 6,
  '전북 정읍': 1,
  '제주 서귀포': 1,
  '제주 제주': 11,
  '충남 계룡': 0,
  '충남 공주': 1,
  '충남 논산': 0,
  '충남 당진': 1,
  '충남 보령': 1,
  '충남 서산': 2,
  '충남 아산': 2,
  '충남 천안': 10,
  '충북 제천': 3,
  '충북 청주': 12,
  '충북 충주': 0},
 {'강원 강릉': 5,
  '강원 동해': 4,
  '강원 삼척': 6,
  '강원 속초': 3,
  '강원 원주': 6,
  '강원 춘천': 3,
  '강원 태백': 0,
  '경기 고양': 40,
  '경기 과천': 1,
  '경기 광명': 6,
  '경기 광주': 6,
  '경기 구리': 9,
  '경기 군포': 7,
  '경기 김포': 13,
  '경기 남양주': 26,
  '경기 동두천': 1,
  '경기 부천': 38,
  '경기 성남': 29,
  '경기 수원': 40,
  '경기 시흥': 25,
  '경기 안산': 30,
  '경기 안성': 4,
  '경기 안양': 12,
  '경기 양주': 8,
  '경기 여주': 2,
  '경기 오산': 4,
  '경기 용인': 15,
  '경기 의왕': 5,
  '경기 의정부': 22,
  '경기 이천': 10,
  '경기 파주': 9,
  '경기 평택': 19,
  '경기 포천': 17,
  '경기 하남': 4,
  '경기 화성': 14,
  '경남 거제': 12,
  '경남 김해': 9,
  '경남 마산': 0,
  '경남 밀양': 2,
  '경남 사천': 7,
  '경남 양산': 9,
  '경남 진주': 12,
  '경남 창원': 33,
  '경남 통영': 0,
  '경북 경산': 5,
  '경북 경주': 6,
  '경북 구미': 10,
  '경북 김천': 4,
  '경북 문경': 2,
  '경북 상주': 2,
  '경북 안동': 8,
  '경북 영주': 6,
  '경북 영천': 3,
  '경북 포항': 16,
  '광주': 48,
  '기타도시': 4,
  '대구': 86,
  '대전': 41,
  '도시이외': 148,
  '범죄대분류': '강력범죄',
  '범죄중분류': '방화',
  '부산': 117,
  '서울': 315,
  '세종': 5,
  '울산': 36,
  '인천': 94,
  '전남 광양': 3,
  '전남 나주': 0,
  '전남 목포': 8,
  '전남 순천': 7,
  '전남 여수': 13,
  '전북 군산': 9,
  '전북 김제': 5,
  '전북 남원': 3,
  '전북 익산': 10,
  '전북 전주': 11,
  '전북 정읍': 6,
  '제주 서귀포': 12,
  '제주 제주': 23,
  '충남 계룡': 0,
  '충남 공주': 3,
  '충남 논산': 8,
  '충남 당진': 4,
  '충남 보령': 4,
  '충남 서산': 5,
  '충남 아산': 4,
  '충남 천안': 22,
  '충북 제천': 3,
  '충북 청주': 23,
  '충북 충주': 4},
 {'강원 강릉': 832,
  '강원 동해': 288,
  '강원 삼척': 188,
  '강원 속초': 344,
  '강원 원주': 1785,
  '강원 춘천': 1132,
  '강원 태백': 130,
  '경기 고양': 3287,
  '경기 과천': 170,
  '경기 광명': 1234,
  '경기 광주': 1072,
  '경기 구리': 1042,
  '경기 군포': 944,
  '경기 김포': 1082,
  '경기 남양주': 1888,
  '경기 동두천': 410,
  '경기 부천': 5048,
  '경기 성남': 3941,
  '경기 수원': 6487,
  '경기 시흥': 1791,
  '경기 안산': 4154,
  '경기 안성': 844,
  '경기 안양': 2142,
  '경기 양주': 719,
  '경기 여주': 417,
  '경기 오산': 1164,
  '경기 용인': 2791,
  '경기 의왕': 307,
  '경기 의정부': 2304,
  '경기 이천': 655,
  '경기 파주': 1136,
  '경기 평택': 2160,
  '경기 포천': 580,
  '경기 하남': 575,
  '경기 화성': 2178,
  '경남 거제': 1395,
  '경남 김해': 2739,
  '경남 마산': 2,
  '경남 밀양': 313,
  '경남 사천': 358,
  '경남 양산': 1205,
  '경남 진주': 2032,
  '경남 창원': 5860,
  '경남 통영': 602,
  '경북 경산': 1174,
  '경북 경주': 1297,
  '경북 구미': 2212,
  '경북 김천': 506,
  '경북 문경': 227,
  '경북 상주': 322,
  '경북 안동': 679,
  '경북 영주': 245,
  '경북 영천': 298,
  '경북 포항': 2496,
  '광주': 8438,
  '기타도시': 643,
  '대구': 12759,
  '대전': 9495,
  '도시이외': 11754,
  '범죄대분류': '절도범죄',
  '범죄중분류': '절도',
  '부산': 20136,
  '서울': 55280,
  '세종': 638,
  '울산': 5449,
  '인천': 10679,
  '전남 광양': 461,
  '전남 나주': 46,
  '전남 목포': 1520,
  '전남 순천': 1188,
  '전남 여수': 1049,
  '전북 군산': 1470,
  '전북 김제': 344,
  '전북 남원': 276,
  '전북 익산': 1391,
  '전북 전주': 3402,
  '전북 정읍': 565,
  '제주 서귀포': 921,
  '제주 제주': 3309,
  '충남 계룡': 53,
  '충남 공주': 423,
  '충남 논산': 634,
  '충남 당진': 1325,
  '충남 보령': 681,
  '충남 서산': 769,
  '충남 아산': 1487,
  '충남 천안': 3945,
  '충북 제천': 524,
  '충북 청주': 4691,
  '충북 충주': 925},
 {'강원 강릉': 352,
  '강원 동해': 202,
  '강원 삼척': 155,
  '강원 속초': 174,
  '강원 원주': 514,
  '강원 춘천': 379,
  '강원 태백': 82,
  '경기 고양': 490,
  '경기 과천': 22,
  '경기 광명': 147,
  '경기 광주': 237,
  '경기 구리': 181,
  '경기 군포': 142,
  '경기 김포': 160,
  '경기 남양주': 392,
  '경기 동두천': 102,
  '경기 부천': 524,
  '경기 성남': 734,
  '경기 수원': 938,
  '경기 시흥': 295,
  '경기 안산': 694,
  '경기 안성': 141,
  '경기 안양': 396,
  '경기 양주': 157,
  '경기 여주': 130,
  '경기 오산': 149,
  '경기 용인': 454,
  '경기 의왕': 57,
  '경기 의정부': 326,
  '경기 이천': 161,
  '경기 파주': 261,
  '경기 평택': 460,
  '경기 포천': 229,
  '경기 하남': 104,
  '경기 화성': 410,
  '경남 거제': 490,
  '경남 김해': 595,
  '경남 마산': 1,
  '경남 밀양': 134,
  '경남 사천': 194,
  '경남 양산': 307,
  '경남 진주': 408,
  '경남 창원': 1187,
  '경남 통영': 321,
  '경북 경산': 248,
  '경북 경주': 347,
  '경북 구미': 508,
  '경북 김천': 200,
  '경북 문경': 100,
  '경북 상주': 127,
  '경북 안동': 257,
  '경북 영주': 134,
  '경북 영천': 118,
  '경북 포항': 616,
  '광주': 1162,
  '기타도시': 149,
  '대구': 2736,
  '대전': 1516,
  '도시이외': 3941,
  '범죄대분류': '폭력범죄',
  '범죄중분류': '상해',
  '부산': 4675,
  '서울': 7174,
  '세종': 117,
  '울산': 1353,
  '인천': 2179,
  '전남 광양': 194,
  '전남 나주': 5,
  '전남 목포': 415,
  '전남 순천': 354,
  '전남 여수': 347,
  '전북 군산': 283,
  '전북 김제': 65,
  '전북 남원': 101,
  '전북 익산': 246,
  '전북 전주': 496,
  '전북 정읍': 108,
  '제주 서귀포': 269,
  '제주 제주': 532,
  '충남 계룡': 24,
  '충남 공주': 137,
  '충남 논산': 155,
  '충남 당진': 215,
  '충남 보령': 137,
  '충남 서산': 179,
  '충남 아산': 341,
  '충남 천안': 522,
  '충북 제천': 172,
  '충북 청주': 798,
  '충북 충주': 265}]

In [ ]:
import numpy as np
import pandas as pd
# 데이터 프레임 형성 및 전처리를 위한 넘파이, 판다스

In [ ]:
crime_df = pd.DataFrame(result['data'])
crime_df
# 지역, 범죄분류가 모두 같은 차원의 컬럼으로 분류가 되어져 있음

,강원 강릉,강원 동해,강원 삼척,강원 속초,강원 원주,강원 춘천,강원 태백,경기 고양,경기 과천,경기 광명,...,충남 공주,충남 논산,충남 당진,충남 보령,충남 서산,충남 아산,충남 천안,충북 제천,충북 청주,충북 충주
0,1,1,0,0,5,3,0,8,2,1,...,0,3,0,3,0,5,4,2,4,1
1,4,1,0,1,5,3,0,9,0,1,...,2,3,1,5,1,4,8,5,15,1
2,8,0,0,0,9,9,0,14,0,4,...,0,4,3,3,6,2,22,2,30,6
3,28,5,10,6,48,10,1,73,0,12,...,14,13,11,10,11,27,82,15,79,15
4,5,1,0,2,2,9,3,9,0,0,...,1,1,0,4,7,2,6,2,4,5
5,56,32,12,20,75,71,8,256,20,77,...,27,39,32,26,48,64,177,26,229,55
6,1,1,3,2,7,7,2,7,0,2,...,1,0,1,1,2,2,10,3,12,0
7,5,4,6,3,6,3,0,40,1,6,...,3,8,4,4,5,4,22,3,23,4
8,832,288,188,344,1785,1132,130,3287,170,1234,...,423,634,1325,681,769,1487,3945,524,4691,925
9,352,202,155,174,514,379,82,490,22,147,...,137,155,215,137,179,341,522,172,798,265

In [ ]:
crime_df.columns
# columns를 통해 데이터에 대한 정보를 재차 확인

Index(['강원 강릉', '강원 동해', '강원 삼척', '강원 속초', '강원 원주', '강원 춘천', '강원 태백', '경기 고양',
       '경기 과천', '경기 광명', '경기 광주', '경기 구리', '경기 군포', '경기 김포', '경기 남양주',
       '경기 동두천', '경기 부천', '경기 성남', '경기 수원', '경기 시흥', '경기 안산', '경기 안성', '경기 안양',
       '경기 양주', '경기 여주', '경기 오산', '경기 용인', '경기 의왕', '경기 의정부', '경기 이천', '경기 파주',
       '경기 평택', '경기 포천', '경기 하남', '경기 화성', '경남 거제', '경남 김해', '경남 마산', '경남 밀양',
       '경남 사천', '경남 양산', '경남 진주', '경남 창원', '경남 통영', '경북 경산', '경북 경주', '경북 구미',
       '경북 김천', '경북 문경', '경북 상주', '경북 안동', '경북 영주', '경북 영천', '경북 포항', '광주',
       '기타도시', '대구', '대전', '도시이외', '범죄대분류', '범죄중분류', '부산', '서울', '세종', '울산',
       '인천', '전남 광양', '전남 나주', '전남 목포', '전남 순천', '전남 여수', '전북 군산', '전북 김제',
       '전북 남원', '전북 익산', '전북 전주', '전북 정읍', '제주 서귀포', '제주 제주', '충남 계룡', '충남 공주',
       '충남 논산', '충남 당진', '충남 보령', '충남 서산', '충남 아산', '충남 천안', '충북 제천', '충북 청주',
       '충북 충주'],
      dtype='object')

In [ ]:
crime_df.groupby(['범죄대분류', '범죄중분류']).sum()
# groupby 함수의 sum()을 통해 범죄대분류와 중분류에 따른 지역별 현황 데이터프레임 형성

                 강원 강릉  강원 동해  강원 삼척  강원 속초  강원 원주  강원 춘천  강원 태백  경기 고양  \
범죄대분류 범죄중분류
강력범죄  강간            28      5     10      6     48     10      1     73
      강도             8      0      0      0      9      9      0     14
      강제추행          56     32     12     20     75     71      8    256
      기타강간강제추행등      1      1      3      2      7      7      2      7
      방화             5      4      6      3      6      3      0     40
      살인기수           1      1      0      0      5      3      0      8
      살인미수등          4      1      0      1      5      3      0      9
      유사강간           5      1      0      2      2      9      3      9
절도범죄  절도           832    288    188    344   1785   1132    130   3287
폭력범죄  상해           352    202    155    174    514    379     82    490

                 경기 과천  경기 광명  ...  충남 공주  충남 논산  충남 당진  충남 보령  충남 서산  충남 아산  \
범죄대분류 범죄중분류                    ...
강력범죄  강간             0     12  ...     14     13     11     10     11     27
      강도             0      4  ...      0      4      3      3      6      2
      강제추행          20     77  ...     27     39     32     26     48     64
      기타강간강제추행등      0      2  ...      1      0      1      1      2      2
      방화             1      6  ...      3      8      4      4      5      4
      살인기수           2      1  ...      0      3      0      3      0      5
      살인미수등          0      1  ...      2      3      1      5      1      4
      유사강간           0      0  ...      1      1      0      4      7      2
절도범죄  절도           170   1234  ...    423    634   1325    681    769   1487
폭력범죄  상해            22    147  ...    137    155    215    137    179    341

                 충남 천안  충북 제천  충북 청주  충북 충주
범죄대분류 범죄중분류
강력범죄  강간            82     15     79     15
      강도            22      2     30      6
      강제추행         177     26    229     55
      기타강간강제추행등     10      3     12      0
      방화            22      3     23      4
      살인기수           4      2      4      1
      살인미수등          8      5     15      1
      유사강간           6      2      4      5
절도범죄  절도          3945    524   4691    925
폭력범죄  상해           522    172    798    265

[10 rows x 88 columns]

1-2. csv 파일을 통해 데이터 불러오기

- 공공데이터 포탈에서 제공하는 csv파일 이용
- api와 동일한 2015년 Data

In [ ]:
# 구글 드라이브 코렙에 마운트 하기
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
# 데이터프레임 형성 및 사용을 위한 판다스

# crime_df2 = pd.read_csv('경찰철_범죄 발생 지역별통계 파일 경로', encoding = 'cp949')
crime_df1 = pd.read_csv('/content/경찰청_범죄 발생 지역별 통계_20151231.csv', encoding = 'cp949')
# 엑셀형식의 csv 파일이므로 cp949 로 encoding 필요

crime_df1.head()

,범죄대분류,범죄중분류,서울,부산,대구,인천,광주,대전,울산,세종,...,경남 밀양,경남 사천,경남 양산,경남 진주,경남 창원,경남 통영,제주 서귀포,제주 제주,기타도시,도시이외
0,강력범죄,살인기수,67,20,13,17,11,8,12,2,...,1,0,2,4,7,2,0,11,7,30
1,강력범죄,살인미수등,96,41,23,34,7,16,11,1,...,5,5,6,0,13,2,1,16,4,44
2,강력범죄,강도,274,161,60,103,44,64,29,0,...,1,4,2,13,26,3,4,29,4,65
3,강력범죄,강간,969,383,216,304,216,181,132,3,...,10,12,35,63,85,11,14,64,18,328
4,강력범죄,유사강간,118,24,21,35,17,14,10,1,...,1,1,3,1,8,1,1,12,0,33

#2. 데이터 전처리

*   지역별 범죄현황 데이터를 보기 편하도록 전처리
*   전처리 과정 중, 필요한 데이터 추가
*   전처리 된 데이터 확인 및 필요한 부분 변경

2-1. 지역별 범죄현황 데이터 전처리 과정

In [ ]:
crime_df2 = crime_df1.copy()
# 원본 훼손 방지를 위한 copy
# crime_df2.head()

In [ ]:
crime_df2 = crime_df1.set_index('범죄대분류')
# 초기 인덱스 번호를 제거
# set_index 를 활용하여 '범죄대분류' col을 index로 변경

# crime_df2.head()

In [ ]:
crime_df2.drop(['범죄중분류'], axis = 1, inplace = True)
# 좀 세세한 느낌이 있어 우선적으로 '범죄중분류' col을 drop 함수를 활용하여 제거
# col 단위이므로 axis = 1 로 설정

crime_df2.head()

,서울,부산,대구,인천,광주,대전,울산,세종,경기 고양,경기 과천,...,경남 밀양,경남 사천,경남 양산,경남 진주,경남 창원,경남 통영,제주 서귀포,제주 제주,기타도시,도시이외
범죄대분류,,,,,,,,,,,,,,,,,,,,,
강력범죄,67,20,13,17,11,8,12,2,8,2,...,1,0,2,4,7,2,0,11,7,30
강력범죄,96,41,23,34,7,16,11,1,9,0,...,5,5,6,0,13,2,1,16,4,44
강력범죄,274,161,60,103,44,64,29,0,14,0,...,1,4,2,13,26,3,4,29,4,65
강력범죄,969,383,216,304,216,181,132,3,73,0,...,10,12,35,63,85,11,14,64,18,328
강력범죄,118,24,21,35,17,14,10,1,9,0,...,1,1,3,1,8,1,1,12,0,33

In [ ]:
crime_df2 = crime_df2.groupby('범죄대분류').sum()
# '범죄대분류' index 가 '범죄중분류'의 제거로 인해 넓게 퍼져있음
# 따라서 groupby 함수를 이용하여 '범죄대분류' 단위로 값을 합해줌

crime_df2.head()

,서울,부산,대구,인천,광주,대전,울산,세종,경기 고양,경기 과천,...,경남 밀양,경남 사천,경남 양산,경남 진주,경남 창원,경남 통영,제주 서귀포,제주 제주,기타도시,도시이외
범죄대분류,,,,,,,,,,,,,,,,,,,,,
강력범죄,6215,1774,1084,1542,860,698,532,46,416,23,...,41,53,117,155,357,58,65,331,67,1467
교통범죄,74958,35841,39725,31163,23412,13556,16600,1056,11926,720,...,1216,2517,3759,3351,12650,2936,3581,10857,2325,43877
기타범죄,41752,19868,9766,13677,5301,4602,4881,462,3473,174,...,410,1040,978,933,3643,1594,1331,3130,1341,17797
노동범죄,215,190,31,28,13,14,63,0,13,0,...,0,1,10,0,19,43,3,6,1,45
마약범죄,1360,759,393,557,69,78,67,2,82,4,...,43,24,25,90,122,10,6,20,16,509

- 각 지역이 경기 수원, 경기 과천, 경남 밀양 등으로 행정 구역별로 나눠져있지 않음
- 따라서 각 지역을 행정 구역별로 합치기 위한 과정이 필요

In [ ]:
## case 1. 같은 방법을 모든 지역에 각각 적용하며 합치기..
# 오타, 수정 등에 어려움 발생 !
# 경기도에서 마지막에 지울 때, 경기도로 변경했던 col 까지 제거되기도 함 ..
# 해결은 완료했으나, 자동화를 위한 함수를 활용 할 수는 없을까?

# col_경기 = list(crime_df2.filter(regex='경기'))
# crime_df2['경기도'] = crime_df2[col_경기].sum(axis=1)
# crime_df2 = crime_df2[crime_df2.columns.drop(col_경기)]

# col_전남 = list(crime_df2.filter(regex='전남'))
# crime_df2['전라남도'] = crime_df2[col_전남].sum(axis=1)
# crime_df2 = crime_df2[crime_df2.columns.drop(col_전남)]

# col_강원 = list(crime_df2.filter(regex='강원'))
# crime_df2['강원도'] = crime_df2[col_강원].sum(axis=1)
# crime_df2 = crime_df2[crime_df2.columns.drop(col_강원)]

# col_충남 = list(crime_df2.filter(regex='충남'))
# crime_df2['충청남도'] = crime_df2[col_충남].sum(axis=1)
# crime_df2 = crime_df2[crime_df2.columns.drop(col_충남)]

# col_전북 = list(crime_df2.filter(regex='전북'))
# crime_df2['전라북도'] = crime_df2[col_전북].sum(axis=1)
# crime_df2 = crime_df2[crime_df2.columns.drop(col_전북)]

# col_제주 = list(crime_df2.filter(regex='제주 '))
# crime_df2['제주도'] = crime_df2[col_제주].sum(axis=1)
# crime_df2 = crime_df2[crime_df2.columns.drop(col_제주)]

# col_경북 = list(crime_df2.filter(regex='경북'))
# crime_df2['경상북도'] = crime_df2[col_경북].sum(axis=1)
# crime_df2 = crime_df2[crime_df2.columns.drop(col_경북)]

# col_충북 = list(crime_df2.filter(regex='충북'))
# crime_df2['충청북도'] = crime_df2[col_충북].sum(axis=1)
# crime_df2 = crime_df2[crime_df2.columns.drop(col_충북)]

# col_경남 = list(crime_df2.filter(regex='경남'))
# crime_df2['경상남도'] = crime_df2[col_경남].sum(axis=1)
# crime_df2 = crime_df2[crime_df2.columns.drop(col_경남)]
# crime_df2.columns

In [ ]:
## case 2 : 자동화를 위한 merge 함수 제작

def merge(df, region_old, region_new): 
    #데이터프레임, 바꿀 지역명, 새 지역명
    #도시를 하나씩 넣거나, 리스트로 한꺼번에 넣어 구분함
    if isinstance(region_old, str) and isinstance(region_new, str): 
        ro = region_old
        rn = region_new
        col = list(df.filter(regex=ro)) 
        #바꿀 지역명을 포함한 모든 col 을 list로 반환
        df[rn] = df[col].sum(axis=1)
        # 새로운 지역명으로 col 변수를 추가
        # 해당 col의 값은 원래 지역명들의 값을 합한 값
        df.drop(columns = col, inplace=True)
        # 원래 존재하던 여러 개의 지역명 제거
        return df

    elif isinstance(region_old, list) and isinstance(region_new, list):
        # 리스트에서 하나씩 꺼내서 작업
        for i, ro in enumerate(region_old):
            col = list(df.filter(regex=(ro)))
            df[region_new[i]] =  df[col].sum(axis=1)
            df.drop(columns =  col, inplace=True)
        return df

    else :
        print("제대로 입력해주세요.")


list_old = ['경기', '전남', '강원', '충남', '전북', '제주', '경북', '충북', '경남']
# 바꾸고자 하는 지역명의 앞부분 값 list
# 경기 수원, 경기 과천 등을 경기도로 바꾸고 싶음
# 따라서 '경기' 라는 말이 들어가는 col을 선택
# 다른 지역명들도 동일

list_new = ['경기도','전라남도','강원도','충청남도','전라북도','제주도','경상북도','충청북도','경상남도']
# 바꾸어질 지역명의 이름 list

merge(crime_df2, list_old, list_new)

,서울,부산,대구,인천,광주,대전,울산,세종,기타도시,도시이외,경기도,전라남도,강원도,충청남도,전라북도,제주도,경상북도,충청북도,경상남도
범죄대분류,,,,,,,,,,,,,,,,,,,
강력범죄,6215,1774,1084,1542,860,698,532,46,67,1467,5815,455,504,755,664,396,832,541,1087
교통범죄,74958,35841,39725,31163,23412,13556,16600,1056,2325,43877,141506,17446,18416,19363,16007,14438,32309,14713,39954
기타범죄,41752,19868,9766,13677,5301,4602,4881,462,1341,17797,45409,5692,4548,7552,6122,4461,7403,3978,11585
노동범죄,215,190,31,28,13,14,63,0,1,45,243,42,24,19,45,9,53,9,101
마약범죄,1360,759,393,557,69,78,67,2,16,509,1399,57,110,145,48,26,204,154,458
병역범죄,4591,959,800,1200,371,630,382,86,155,808,4595,310,265,721,381,242,772,391,1067
보건범죄,3941,1832,417,654,760,204,230,15,36,843,3131,168,232,225,410,168,405,196,735
선거범죄,24,24,18,19,9,8,15,5,3,267,83,29,15,33,34,23,63,18,70
안보범죄,38,4,4,20,3,4,2,0,1,6,16,2,1,13,1,0,1,0,5
절도범죄,55280,20136,12759,10679,8438,9495,5449,638,643,11754,50522,4264,4699,9317,7448,4230,9456,6140,14506
지능범죄,72851,25247,14195,16938,9724,9112,6898,680,2495,17856,71370,6195,5655,9766,8084,4391,11519,5886,17259
특별경제범죄,22075,13868,3421,5751,2535,1635,1289,187,1631,3027,17679,1063,1307,1776,1417,1251,2400,1045,2972
폭력범죄,65247,20928,14708,18054,9602,8839,8277,452,825,15985,71930,6840,8036,7993,8181,5518,11317,7160,16055
풍속범죄,6741,2085,1418,1580,592,689,403,29,119,1050,5306,413,309,648,636,407,752,449,865
환경범죄,53,198,19,69,8,13,53,2,30,503,1192,63,57,90,80,46,123,50,306

In [ ]:
crime_df2.columns
# col 명이 제대로 바뀌었는 지 확인

Index(['서울', '부산', '대구', '인천', '광주', '대전', '울산', '세종', '기타도시', '도시이외', '경기도',
       '전라남도', '강원도', '충청남도', '전라북도', '제주도', '경상북도', '충청북도', '경상남도'],
      dtype='object')

In [ ]:
# 나중에 시각화할 경우, 도시의 이름을 맞추는 과정이 필요함 !
# 따라서 미리 행정구역명을 풀네임으로 변경
# # 도시이외를 기타도시와 합침

crime_df2.rename(columns = {
    '서울':'서울특별시',
    '경기':'경기도',
    '인천':'인천광역시',
    '대구':'대구광역시',
    '부산':'부산광역시',
    '경남':'경상남도',
    '충남':'충청남도',
    '경북':'경상북도',
    '충북':'충청북도',
    '대전':'대전광역시',
    '강원':'강원도',
    '전북':'전라북도',
    '광주':'광주광역시',
    '울산':'울산광역시',
    '전남':'전라남도',
    '제주':'제주특별자치도',
    '세종':'세종특별자치시',
    '기타도시' : '기타도시',
    '도시이외' : '기타도시' 
}, inplace = True)

In [ ]:
# 기타도시는 시각화 과정에서 표현하기 어려우므로 삭제
crime_df2 = crime_df2.drop('기타도시', axis = 1)

- 범죄의 종류가 다소 많음.
- 따라서 필요한 부분만 남기거나 합치는 과정 필요

In [ ]:
crime_df2.index

Index(['강력범죄', '교통범죄', '기타범죄', '노동범죄', '마약범죄', '병역범죄', '보건범죄', '선거범죄', '안보범죄',
       '절도범죄', '지능범죄', '특별경제범죄', '폭력범죄', '풍속범죄', '환경범죄'],
      dtype='object', name='범죄대분류')

In [ ]:
## 기타범죄의 항목에 노동범죄, 선거범죄, 안보범죄, 환경범죄, 풍속범죄를 포함시키기로 결정
# 범죄의 분류는 총 10개
# 강력범죄, 교통범죄, 노동범죄, 마약범죄, 병역범죄, 절도범죄, 지능범죄, 특별경제범죄, 폭력범죄, 기타범죄

crime_df2.loc['기타범죄'] = (crime_df2.loc['노동범죄'] + crime_df2.loc['선거범죄'] + crime_df2.loc['안보범죄'] 
                                         + crime_df2.loc['환경범죄'] + crime_df2.loc['풍속범죄'] + crime_df2.loc['기타범죄'])

crime_df2 = crime_df2.drop(['노동범죄','선거범죄','안보범죄','환경범죄','풍속범죄'])

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1732: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)
/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:723: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value, self.name)

In [ ]:
crime_df2.index
# 제대로 변경이 되었는 지 확인

Index(['강력범죄', '교통범죄', '기타범죄', '마약범죄', '병역범죄', '보건범죄', '절도범죄', '지능범죄',
       '특별경제범죄', '폭력범죄'],
      dtype='object', name='범죄대분류')

In [ ]:
crime_df2

,서울특별시,부산광역시,대구광역시,인천광역시,광주광역시,대전광역시,울산광역시,세종특별자치시,경기도,전라남도,강원도,충청남도,전라북도,제주도,경상북도,충청북도,경상남도
범죄대분류,,,,,,,,,,,,,,,,,
강력범죄,6215,1774,1084,1542,860,698,532,46,5815,455,504,755,664,396,832,541,1087
교통범죄,74958,35841,39725,31163,23412,13556,16600,1056,141506,17446,18416,19363,16007,14438,32309,14713,39954
기타범죄,48823,22369,11256,15393,5926,5330,5417,498,52249,6241,4954,8355,6918,4946,8395,4504,12932
마약범죄,1360,759,393,557,69,78,67,2,1399,57,110,145,48,26,204,154,458
병역범죄,4591,959,800,1200,371,630,382,86,4595,310,265,721,381,242,772,391,1067
보건범죄,3941,1832,417,654,760,204,230,15,3131,168,232,225,410,168,405,196,735
절도범죄,55280,20136,12759,10679,8438,9495,5449,638,50522,4264,4699,9317,7448,4230,9456,6140,14506
지능범죄,72851,25247,14195,16938,9724,9112,6898,680,71370,6195,5655,9766,8084,4391,11519,5886,17259
특별경제범죄,22075,13868,3421,5751,2535,1635,1289,187,17679,1063,1307,1776,1417,1251,2400,1045,2972
폭력범죄,65247,20928,14708,18054,9602,8839,8277,452,71930,6840,8036,7993,8181,5518,11317,7160,16055

In [ ]:
# 범죄대분류 라는 인덱스 네임이 보기 좋지 않음.
# 따라서 인덱스 네임 삭제

# df.index.names = ['Date'] #코드예시
crime_df2.index.names = ['']
crime_df2.head()

,서울특별시,부산광역시,대구광역시,인천광역시,광주광역시,대전광역시,울산광역시,세종특별자치시,경기도,전라남도,강원도,충청남도,전라북도,제주도,경상북도,충청북도,경상남도,기타범죄
,,,,,,,,,,,,,,,,,,
강력범죄,6215,1774,1084,1542,860,698,532,46,5815,455,504,755,664,396,832,541,1087,NaN
교통범죄,74958,35841,39725,31163,23412,13556,16600,1056,141506,17446,18416,19363,16007,14438,32309,14713,39954,NaN
기타범죄,41752,19868,9766,13677,5301,4602,4881,462,45409,5692,4548,7552,6122,4461,7403,3978,11585,NaN
마약범죄,1360,759,393,557,69,78,67,2,1399,57,110,145,48,26,204,154,458,NaN
병역범죄,4591,959,800,1200,371,630,382,86,4595,310,265,721,381,242,772,391,1067,NaN

- 모든 범죄의 총 발생 건수가 제일 많은 지역이 어디지?

In [ ]:
crime_df3 = crime_df2.copy()
# 원본 훼손 방지를 위한 copy

In [ ]:
crime_df3.T

In [ ]:
# loc 를 이용하여 인덱스 별로 범죄 발생건 수를 합치고, 각 지역명 변수에 저장 !
# 인덱스별로 합치는 것이 편리하므로 .. T(전치행렬) 이용

서울특별시 = crime_df3.T.loc['서울특별시'].sum()
부산광역시 = crime_df3.T.loc['부산광역시'].sum()
대구광역시 = crime_df3.T.loc['대구광역시'].sum()
인천광역시 = crime_df3.T.loc['인천광역시'].sum()
광주광역시 = crime_df3.T.loc['광주광역시'].sum()
대전광역시 = crime_df3.T.loc['대전광역시'].sum()
울산광역시 = crime_df3.T.loc['울산광역시'].sum()
세종특별자치시 = crime_df3.T.loc['세종특별자치시'].sum()
경기도 = crime_df3.T.loc['경기도'].sum()
전라남도 = crime_df3.T.loc['전라남도'].sum()
강원도 = crime_df3.T.loc['강원도'].sum()
충청남도 = crime_df3.T.loc['충청남도'].sum()
전라북도 = crime_df3.T.loc['전라북도'].sum()
제주도 = crime_df3.T.loc['제주도'].sum()
경상북도 = crime_df3.T.loc['경상북도'].sum()
충청북도 = crime_df3.T.loc['충청북도'].sum()
경상남도 = crime_df3.T.loc['경상남도'].sum()

# data_local 이라는 딕셔너리에 총 발생건수와 지역명 저장

data_local = {'서울특별시' : 서울특별시,
              '부산광역시' : 부산광역시,
              '대구광역시' : 대구광역시,
              '인천광역시' : 인천광역시,
              '광주광역시' : 광주광역시,
              '대전광역시' : 대전광역시,
              '울산광역시' : 울산광역시,
              '세종특별자치시' : 세종특별자치시,
              '경기도' : 경기도,
              '강원도' : 강원도,
              '전라북도' : 전라북도,
              '전라남도' : 전라남도,              
              '경상북도' : 경상북도,
              '충청북도' : 충청북도,
              '충청남도' : 충청남도,
              '경상북도' : 경상북도,              
              '경상남도' : 경상남도,
              '제주특별자치도' : 제주도                            
            }

data_local

{'강원도': 43772,
 '경기도': 413356,
 '경상남도': 105678,
 '경상북도': 76617,
 '광주광역시': 61072,
 '대구광역시': 97268,
 '대전광역시': 48849,
 '부산광역시': 141212,
 '서울특별시': 348270,
 '세종특별자치시': 3624,
 '울산광역시': 44605,
 '인천광역시': 100215,
 '전라남도': 42490,
 '전라북도': 48762,
 '제주특별자치도': 35121,
 '충청남도': 57613,
 '충청북도': 40204}

In [ ]:
data_local = {'지역별 범죄 발생건수' : data_local}
# 지역별 범죄현황이라는 key 안에 딕셔너리 값이 들어가도록 변경

In [ ]:
data_local_df = pd.DataFrame(data_local)
# 지역별 범죄현황 데이터 프레임 형성
data_local_df

2-2. 전처리 과정 중, 필요를 느낀 데이터 추가

지역별 인구수


* 단순한 지역별 범죄건수 데이터가 의미가 있을까? 
* 인구수가 많으면 당연히 범죄건수도 높은 것이 아닐까?
* 인구수까지 참고하는 것이 필요하지 않을까?
* https://kosis.kr/statHtml/statHtml.do?orgId=101&tblId=DT_1B040A3
* 2015.12.01 기준 Data

In [ ]:
# population = pd.read_csv('지역별 인구수 csv 파일 경로', encoding = 'cp949')
population = pd.read_csv('/content/drive/MyDrive/IT_Study/미니플젝01_범죄/지역별_인구수.csv', encoding = 'cp949')
# 엑셀 파일이므로 encoding
# population

In [ ]:
# col 명에 2015.12 라는 곳이 총인구수에 해당하는 곳
# 따라서 col 이름으로 변경
population.rename(columns={'2015.12':'총 인구수'},inplace=True)
# population

In [ ]:
# 다른 데이터들과 합치기 편하도록 만들어 놓은 데이터프레임의 인덱스를 행정구역명으로 변경
# 만들어 놓은 데이터프레임 : 범죄 데이터 
crime_df3 = crime_df2.T.reset_index()
crime_df3.rename(columns = {'index': '행정구역(시군구)별'}, inplace=True)
crime_df3.head()

In [ ]:
crime_df3 = crime_df3.sort_values(by =['행정구역(시군구)별']).reset_index(drop=True) 
# population 데이터와의 비교를 위해 범죄 데이터를 도시이름별로 정렬
crime_df3

In [ ]:
population = population.sort_values(by =['행정구역(시군구)별']).reset_index(drop=True) 
#인구수 데이터 도시별 정렬
population

In [ ]:
# 범죄 데이터와 인구수 데이터의 맞지 않는 지역 인덱스명 : 제주도
# 인구수 데이터의 12번째(전국), 18번째 행 불필요 !
# 따라서 index 이름 변경 및 행 삭제
population.iloc[15,0] = '제주도'
population = population.drop(index = [12,18]).reset_index(drop=True) 
# population

In [ ]:
crime_df3

In [ ]:
# 인구수 데이터의 우측 두 개의 col (남, 여 인구수) 불필요
# 총 인구수 col 만 가져와서 사용
population.loc[:,'행정구역(시군구)별': '총 인구수']
crime_df = crime_df3.merge(population.loc[:,'행정구역(시군구)별': '총 인구수'], on ='행정구역(시군구)별')
# merge 함수를 이용하여 데이터 합치기
crime_df

,행정구역(시군구)별,강력범죄,교통범죄,기타범죄,마약범죄,병역범죄,보건범죄,절도범죄,지능범죄,특별경제범죄,폭력범죄,총 인구수
0,강원도,504,18416,4548,110,265,232,4699,5655,1307,8036,1549507.0
1,경기도,5815,141506,45409,1399,4595,3131,50522,71370,17679,71930,12522606.0
2,경상남도,1087,39954,11585,458,1067,735,14506,17259,2972,16055,3364702.0
3,경상북도,832,32309,7403,204,772,405,9456,11519,2400,11317,2702826.0
4,광주광역시,860,23412,5301,69,371,760,8438,9724,2535,9602,1472199.0
5,대구광역시,1084,39725,9766,393,800,417,12759,14195,3421,14708,2487829.0
6,대전광역시,698,13556,4602,78,630,204,9495,9112,1635,8839,1518775.0
7,부산광역시,1774,35841,19868,759,959,1832,20136,25247,13868,20928,3513777.0
8,서울특별시,6215,74958,41752,1360,4591,3941,55280,72851,22075,65247,10022181.0
9,세종특별자치시,46,1056,462,2,86,15,638,680,187,452,210884.0
10,울산광역시,532,16600,4881,67,382,230,5449,6898,1289,8277,1173534.0
11,인천광역시,1542,31163,13677,557,1200,654,10679,16938,5751,18054,2925815.0
12,전라남도,455,17446,5692,57,310,168,4264,6195,1063,6840,1908996.0
13,전라북도,664,16007,6122,48,381,410,7448,8084,1417,8181,1869711.0
14,제주도,396,14438,4461,26,242,168,4230,4391,1251,5518,624395.0
15,충청남도,755,19363,7552,145,721,225,9317,9766,1776,7993,2077649.0
16,충청북도,541,14713,3978,154,391,196,6140,5886,1045,7160,1583952.0

범죄건수가 아닌, 범죄율로 비교해봐야 하지 않을까?

*   총 인구수 (population ) 이용
*   10만명당 총인구 비율 = 총인구수 / 100,000

In [ ]:
# 인구수 데이터에서 필요없는 col 삭제 및 데이터 타입 변경
population.drop(columns = ['2015.12.1', '2015.12.2'], inplace = True)
# population

In [ ]:
# 총인구수가 object 이므로 타입 변경 필요
# population.info()
population['총 인구수'] = population['총 인구수'].astype(float)

In [ ]:
population['10만명당 총인구수 비율'] = population['총 인구수']/100000
population

In [ ]:
df1 = crime_df.copy()

In [ ]:
# 계산을 위해 10만명당 총인구수 데이터와 범죄 데이터 합치기
df1 = df1.merge(population[['행정구역(시군구)별', '10만명당 총인구수 비율']], on='행정구역(시군구)별')
df1

In [ ]:
# 각 범죄별 범죄비율 계산 및 col 추가
df1['강력범죄율'] = round(df1['강력범죄']/df1['10만명당 총인구수 비율'])
df1['교통범죄율'] = round(df1['교통범죄']/df1['10만명당 총인구수 비율'])
df1['마약범죄율'] = round(df1['마약범죄']/df1['10만명당 총인구수 비율'])
df1['병역범죄율'] = round(df1['병역범죄']/df1['10만명당 총인구수 비율'])
df1['보건범죄율'] = round(df1['보건범죄']/df1['10만명당 총인구수 비율'])
df1['절도범죄율'] = round(df1['절도범죄']/df1['10만명당 총인구수 비율'])
df1['지능범죄율'] = round(df1['지능범죄']/df1['10만명당 총인구수 비율'])
df1['특별경제범죄율'] = round(df1['특별경제범죄']/df1['10만명당 총인구수 비율'])
df1['폭력범죄율'] = round(df1['폭력범죄']/df1['10만명당 총인구수 비율'])
df1['기타범죄율'] = round(df1['기타범죄']/df1['10만명당 총인구수 비율'])

df1

In [ ]:
df1.drop(['10만명당 총인구수 비율', '총 인구수','강력범죄', '교통범죄', '마약범죄','병역범죄', '보건범죄','절도범죄','지능범죄','특별경제범죄',	'폭력범죄',	'기타범죄'], axis=1, inplace=True)
# df1 보기 좋게 범죄율만 나오도록 정리
df1

In [ ]:
# 강력범죄율, 절도범죄율, 폭력범죄율, 주요범죄율로 col 정리하기
# 나머지 범죄율은 크게 비중을 차지 하지 않으므로 제거 !
df1['주요범죄율'] = (df1['강력범죄율'] + df1['절도범죄율'] + df1['폭력범죄율'])

df1 = df1.drop(columns = ['교통범죄율','마약범죄율','병역범죄율','보건범죄율','지능범죄율', '특별경제범죄율', '기타범죄율'], axis = 1)

df1

In [ ]:
# 범죄율의 각 데이터 타입을 float 에서 int로 변경
# df1.info()
df1['강력범죄율'] = df1['강력범죄율'].astype(int)
df1['절도범죄율'] = df1['절도범죄율'].astype(int)
df1['폭력범죄율'] = df1['폭력범죄율'].astype(int)
df1['주요범죄율'] = df1['주요범죄율'].astype(int)

In [ ]:
crime_df = crime_df.merge(df1[:],on='행정구역(시군구)별')
crime_df

,행정구역(시군구)별,강력범죄,교통범죄,기타범죄,마약범죄,병역범죄,보건범죄,절도범죄,지능범죄,특별경제범죄,폭력범죄,총 인구수,강력범죄율,절도범죄율,폭력범죄율,주요범죄율
0,강원도,504,18416,4548,110,265,232,4699,5655,1307,8036,1549507.0,33,303,519,855
1,경기도,5815,141506,45409,1399,4595,3131,50522,71370,17679,71930,12522606.0,46,403,574,1023
2,경상남도,1087,39954,11585,458,1067,735,14506,17259,2972,16055,3364702.0,32,431,477,940
3,경상북도,832,32309,7403,204,772,405,9456,11519,2400,11317,2702826.0,31,350,419,800
4,광주광역시,860,23412,5301,69,371,760,8438,9724,2535,9602,1472199.0,58,573,652,1283
5,대구광역시,1084,39725,9766,393,800,417,12759,14195,3421,14708,2487829.0,44,513,591,1148
6,대전광역시,698,13556,4602,78,630,204,9495,9112,1635,8839,1518775.0,46,625,582,1253
7,부산광역시,1774,35841,19868,759,959,1832,20136,25247,13868,20928,3513777.0,50,573,596,1219
8,서울특별시,6215,74958,41752,1360,4591,3941,55280,72851,22075,65247,10022181.0,62,552,651,1265
9,세종특별자치시,46,1056,462,2,86,15,638,680,187,452,210884.0,22,303,214,539
10,울산광역시,532,16600,4881,67,382,230,5449,6898,1289,8277,1173534.0,45,464,705,1214
11,인천광역시,1542,31163,13677,557,1200,654,10679,16938,5751,18054,2925815.0,53,365,617,1035
12,전라남도,455,17446,5692,57,310,168,4264,6195,1063,6840,1908996.0,24,223,358,605
13,전라북도,664,16007,6122,48,381,410,7448,8084,1417,8181,1869711.0,36,398,438,872
14,제주도,396,14438,4461,26,242,168,4230,4391,1251,5518,624395.0,63,677,884,1624
15,충청남도,755,19363,7552,145,721,225,9317,9766,1776,7993,2077649.0,36,448,385,869
16,충청북도,541,14713,3978,154,391,196,6140,5886,1045,7160,1583952.0,34,388,452,874

지역별 인구밀도
- 인구수보다는 인구밀도가 더 쓸모가 있지 않을까?

In [ ]:
# pop_density = pd.read_csv('인구밀도 csv 파일 경로', encoding = 'cp949')
pop_density = pd.read_csv('/content/drive/MyDrive/IT_Study/미니플젝01_범죄/시도별_인구밀도.csv', encoding = 'cp949')
# 엑셀 형식의 csv 이므로 encoding
pop_density

In [ ]:
# col 이름 변경
# 1. '행정구역별'로 되어 있는 col 이름을 '행정구역(시군구)별'로 변경
# 2. '2015'로 되어 있는 col 이름을 '인구밀도'로 변경
pop_density.rename(columns = {'행정구역별' : '행정구역(시군구)별', '2015' : '인구밀도'}, inplace=True)
pop_density

In [ ]:
# 불필요한 인덱스 값 : 전국
pop_density = pop_density.drop(index = [0]).reset_index(drop=True)
pop_density

In [ ]:
# pop_density.loc[:,['행정구역(시군구)별', '인구밀도']]
# crime_df (범죄데이터) 와 합치기
crime_df = crime_df.merge(pop_density[['행정구역(시군구)별','인구밀도']],on='행정구역(시군구)별')
crime_df

,행정구역(시군구)별,강력범죄,교통범죄,기타범죄,마약범죄,병역범죄,보건범죄,절도범죄,지능범죄,특별경제범죄,폭력범죄,총 인구수,강력범죄율,절도범죄율,폭력범죄율,주요범죄율,인구밀도
0,강원도,504,18416,4548,110,265,232,4699,5655,1307,8036,1549507.0,33,303,519,855,90.2
1,경기도,5815,141506,45409,1399,4595,3131,50522,71370,17679,71930,12522606.0,46,403,574,1023,1226.4
2,경상남도,1087,39954,11585,458,1067,735,14506,17259,2972,16055,3364702.0,32,431,477,940,316.4
3,경상북도,832,32309,7403,204,772,405,9456,11519,2400,11317,2702826.0,31,350,419,800,140.8
4,광주광역시,860,23412,5301,69,371,760,8438,9724,2535,9602,1472199.0,58,573,652,1283,2998.8
5,대구광역시,1084,39725,9766,393,800,417,12759,14195,3421,14708,2487829.0,44,513,591,1148,2791.0
6,대전광역시,698,13556,4602,78,630,204,9495,9112,1635,8839,1518775.0,46,625,582,1253,2852.3
7,부산광역시,1774,35841,19868,759,959,1832,20136,25247,13868,20928,3513777.0,50,573,596,1219,4479.9
8,서울특별시,6215,74958,41752,1360,4591,3941,55280,72851,22075,65247,10022181.0,62,552,651,1265,16364.0
9,세종특별자치시,46,1056,462,2,86,15,638,680,187,452,210884.0,22,303,214,539,439.0
10,울산광역시,532,16600,4881,67,382,230,5449,6898,1289,8277,1173534.0,45,464,705,1214,1099.6
11,인천광역시,1542,31163,13677,557,1200,654,10679,16938,5751,18054,2925815.0,53,365,617,1035,2755.5
12,전라남도,455,17446,5692,57,310,168,4264,6195,1063,6840,1908996.0,24,223,358,605,146.1
13,전라북도,664,16007,6122,48,381,410,7448,8084,1417,8181,1869711.0,36,398,438,872,227.4
14,제주도,396,14438,4461,26,242,168,4230,4391,1251,5518,624395.0,63,677,884,1624,327.5
15,충청남도,755,19363,7552,145,721,225,9317,9766,1776,7993,2077649.0,36,448,385,869,256.6
16,충청북도,541,14713,3978,154,391,196,6140,5886,1045,7160,1583952.0,34,388,452,874,214.6

지역별 개인소득


* 인구수도 문제지만, 지역별 개인소득에 따른 차이도 있지 않을까?
* 인구수 데이터와 비슷한 방법으로 개인소득 데이터 전처리
- 2015년 data

In [ ]:
# local_gnp = pd.read_csv('지역별 개인소득 csv 파일 경로', encoding = 'cp949')
local_gnp = pd.read_csv('/content/drive/MyDrive/IT_Study/미니플젝01_범죄/지역별_개인소득.csv', encoding = 'cp949')
# 엑셀 형식의 csv 이므로 encoding
local_gnp

In [ ]:
# 범죄 데이터와 개인소득 데이터의 맞지 않는 지역 인덱스명 : 제주도
# 따라서 인덱스명 변경
local_gnp.시도별[18] =  '제주도'

In [ ]:
# col 이름 변경 및 지역명으로 정렬
local_gnp.rename(columns={'시도별':'행정구역(시군구)별', '2015.1': '지역총소득'}, inplace=True)
local_gnp = local_gnp.sort_values(by =['행정구역(시군구)별']).reset_index(drop=True)
# local_gnp

In [ ]:
# 개인소득 데이터의 10번째, 13번째 열 불필요 !
local_gnp = local_gnp.drop(index = [10,13]).reset_index(drop=True)
local_gnp

In [ ]:
# crime_df (범죄데이터) 와 합치기
local_gnp.loc[:,['행정구역(시군구)별', '지역총소득']]
crime_df = crime_df.merge(local_gnp[['행정구역(시군구)별','지역총소득']],on='행정구역(시군구)별')

In [ ]:
# 불필요한 인덱스 !
# 행정구역으로 인덱스 변경
crime_df.set_index('행정구역(시군구)별',inplace=True)
crime_df.head()

,강력범죄,교통범죄,기타범죄,마약범죄,병역범죄,보건범죄,절도범죄,지능범죄,특별경제범죄,폭력범죄,총 인구수,강력범죄율,절도범죄율,폭력범죄율,주요범죄율,인구밀도,지역총소득
행정구역(시군구)별,,,,,,,,,,,,,,,,,
강원도,504,18416,4548,110,265,232,4699,5655,1307,8036,1549507.0,33,303,519,855,90.2,24761
경기도,5815,141506,45409,1399,4595,3131,50522,71370,17679,71930,12522606.0,46,403,574,1023,1226.4,33028
경상남도,1087,39954,11585,458,1067,735,14506,17259,2972,16055,3364702.0,32,431,477,940,316.4,29523
경상북도,832,32309,7403,204,772,405,9456,11519,2400,11317,2702826.0,31,350,419,800,140.8,32427
광주광역시,860,23412,5301,69,371,760,8438,9724,2535,9602,1472199.0,58,573,652,1283,2998.8,25687

경찰관 수
- 경찰관비율에 따른 범죄발생건수에 차이가 있지 않을까?
- 2015년 data

In [ ]:
# police = pd.read_csv('지역별 경찰관수 csv 파일 경로', encoding = 'cp949')
police = pd.read_csv('/content/drive/MyDrive/IT_Study/미니플젝01_범죄/지역별_경찰관수.csv', encoding = 'cp949')
# 엑셀 형식의 csv 이므로 encoding
police

In [ ]:
# 범죄 데이터와 경찰관수 데이터의 맞지 않는 지역명 : 제주도
# 따라서 지역명 변경
police.loc[19][0] = '제주도'

In [ ]:
# 불필요한 열 삭제 : 0, 1, 2 번째 행 불필요
police = police.drop(index = [0,1,2]).reset_index(drop=True)
# police

In [ ]:
# 경찰관 수 보다는 경찰관 비율을 활용하자 !
# 만명당 경찰관 비율 col : 2015.2
police.rename(columns={'지방청별(1)':'행정구역(시군구)별', '2015.2': '경찰관비율'}, inplace=True)
police

In [ ]:
# 불필요한 col 제거

police = police.drop(columns = ['2015','2015.1','2015.3','2015.4','2015.5','2015.6','2015.7','2015.8','2015.9','2015.10'], axis = 1 )
police

In [ ]:
# 경찰관 데이터 정렬
police = police.sort_values(by =['행정구역(시군구)별']).reset_index(drop=True)

In [ ]:
# crime_df (범죄데이터) 와 합치기
crime_df = crime_df.merge(police.loc[:,'행정구역(시군구)별':'경찰관비율'], on ='행정구역(시군구)별')
# crime_df

In [ ]:
crime_df

,행정구역(시군구)별,강력범죄,교통범죄,기타범죄,마약범죄,병역범죄,보건범죄,절도범죄,지능범죄,특별경제범죄,폭력범죄,총 인구수,강력범죄율,절도범죄율,폭력범죄율,주요범죄율,인구밀도,지역총소득,경찰관비율
0,강원도,504,18416,4548,110,265,232,4699,5655,1307,8036,1549507.0,33,303,519,855,90.2,24761,32
1,경기도,5815,141506,45409,1399,4595,3131,50522,71370,17679,71930,12522606.0,46,403,574,1023,1226.4,33028,16
2,경상남도,1087,39954,11585,458,1067,735,14506,17259,2972,16055,3364702.0,32,431,477,940,316.4,29523,20
3,경상북도,832,32309,7403,204,772,405,9456,11519,2400,11317,2702826.0,31,350,419,800,140.8,32427,24
4,광주광역시,860,23412,5301,69,371,760,8438,9724,2535,9602,1472199.0,58,573,652,1283,2998.8,25687,22
5,대구광역시,1084,39725,9766,393,800,417,12759,14195,3421,14708,2487829.0,44,513,591,1148,2791.0,24660,21
6,대전광역시,698,13556,4602,78,630,204,9495,9112,1635,8839,1518775.0,46,625,582,1253,2852.3,27125,19
7,부산광역시,1774,35841,19868,759,959,1832,20136,25247,13868,20928,3513777.0,50,573,596,1219,4479.9,25773,26
8,서울특별시,6215,74958,41752,1360,4591,3941,55280,72851,22075,65247,10022181.0,62,552,651,1265,16364.0,41857,25.4
9,세종특별자치시,46,1056,462,2,86,15,638,680,187,452,210884.0,22,303,214,539,439.0,44463,12
10,인천광역시,1542,31163,13677,557,1200,654,10679,16938,5751,18054,2925815.0,53,365,617,1035,2755.5,28034,22
11,전라남도,455,17446,5692,57,310,168,4264,6195,1063,6840,1908996.0,24,223,358,605,146.1,32733,34
12,제주도,396,14438,4461,26,242,168,4230,4391,1251,5518,624395.0,63,677,884,1624,327.5,27314,38
13,충청남도,755,19363,7552,145,721,225,9317,9766,1776,7993,2077649.0,36,448,385,869,256.6,35458,23
14,충청북도,541,14713,3978,154,391,196,6140,5886,1045,7160,1583952.0,34,388,452,874,214.6,28839,21

대졸자수
- 만약 지역소득과 연관성이 있다면 .. 교육 정도와의 연관성은 없을까?

In [ ]:
# education = pd.read_csv('지역별 경찰관수 csv 파일 경로', encoding = 'cp949')
education = pd.read_csv('/content/drive/MyDrive/IT_Study/미니플젝01_범죄/대졸자비율_2015.csv', encoding = 'cp949')
# 엑셀 형식의 csv 이므로 encoding
education

In [ ]:
### 비율을 어떤 공식으로 구하신 건지 감이 안잡혀서 못했습니다 ㅜㅜ
## 알려주시면 채워놓겠습니다 !!!

2-3. 전처리 된 데이터 확인 및 부분적인 변경
- info 함수를 통한 타입 확인

In [ ]:
crime_df

In [ ]:
crime_df.info()
# 총 인구수, 지역총소득, 경찰관비율이 object
# 인구밀도 float

In [ ]:
# 총인구수, 지역총소득, 인구밀도는 int로 변경 !
# 경찰관비율은 float으로 변경 !
crime_df['총 인구수'] = crime_df['총 인구수'].astype(int)
crime_df['지역총소득'] = crime_df['지역총소득'].astype(int)
crime_df['인구밀도'] = crime_df['인구밀도'].astype(int)
crime_df['경찰관비율'] = crime_df['경찰관비율'].astype(float)

In [ ]:
crime_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 15 entries, 0 to 14
Data columns (total 19 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   행정구역(시군구)별  15 non-null     object
 1   강력범죄        15 non-null     int64
 2   교통범죄        15 non-null     int64
 3   기타범죄        15 non-null     int64
 4   마약범죄        15 non-null     int64
 5   병역범죄        15 non-null     int64
 6   보건범죄        15 non-null     int64
 7   절도범죄        15 non-null     int64
 8   지능범죄        15 non-null     int64
 9   특별경제범죄      15 non-null     int64
 10  폭력범죄        15 non-null     int64
 11  총 인구수       15 non-null     float64
 12  강력범죄율       15 non-null     int64
 13  절도범죄율       15 non-null     int64
 14  폭력범죄율       15 non-null     int64
 15  주요범죄율       15 non-null     int64
 16  인구밀도        15 non-null     int64
 17  지역총소득       15 non-null     int64
 18  경찰관비율       15 non-null     float64
dtypes: float64(2), int64(16), object(1)
memory usage: 2.3+ KB

In [ ]:
crime_df

# 전처리 한 데이터 저장 및 불러오기

In [ ]:
crime_df.to_csv('crime_final.csv', index = False)
# csv 파일로 저장
# unnamed:0 col 생성이 안되도록 하기 위해 index = False

In [ ]:
crime = pd.read_csv('crime_final.csv')
crime
# 파일 불러오기